### ISSUE TITLE
Amount must be integer error:

### ISSUE THREAD

**Issue by droidekas** [razorpay/razorpay-android-sample-app#1]
Hi,

I am trying to integrate your latest sdk from the downloads page:

I am facing 2 issues:

1. The amount does not appear correctly:
    - I need to multiply by 100 to get a proper denomination
2. No matter what value I enter,I always get Amount should be an integer

**Comment by droidekas** [comment]
The amount should be lesser than 5 in testing, Figured

**Comment by shashankmehta** [comment]
Have a look at this [line](https://github.com/razorpay/razorpay-android-sample-app/blob/cc1e9493f1d80f64df13f9936d9fa16f6c75f172/src/main/java/com/razorpay/sampleapp/PaymentActivity.java#L43). The amount is always in "paisa", no matter which API endpoint you use. You can refer to docs for this [here](https://docs.razorpay.com/docs/checkout-form#checkout-fields).

Examples:
- You pass `100`, the customer pays Rs 1.00
- If you want to charge your customer Rs 512.50, you pass `51250`.
- You cannot charge your customer Rs 512.505

**Comment by harshm90** [comment]
@shashankmehta Hello,
I am getting the amount of 12345 where i want to charge 123.45 but it is still showing me it should be integer :(
how do i do that?
