### ISSUE TITLE
android razorpay sdk integration 

### ISSUE THREAD

**Issue by krmanohar** [razorpay/razorpay-android-sample-app#100]
we have integrated razorpay sdk in our android app 
during testing we observed the following 
if the payment failed for any reason, the screen informing the user that the payment failed disappears in a fraction of a second. we would like to inform users that the payment failed and possibly give an option to retry the payment. the sample app shows this; however the sdk integrated to our app does not show. any pointers as to why this behavior. Objective is to inform user about the payment failure. 
Thanks

**Comment by sumedht** [comment]
@krmanohar For SDK u will get a callback in onPaymentError() and there u can handle it. For a sample app, we are using test key so it is a behavior.
