### ISSUE TITLE
how to disable QR payment method

### ISSUE THREAD

**Issue by SumukhaK** [razorpay/razorpay-android-sample-app#102]
Hello, I'm using `'com.razorpay:checkout:1.5.2'` in my android app. In sandbox version I have observed that Qr mode of payment is available on selected devices(One plus 5t for eg.) and unavailable to the rest of the devices. How can I permanently disable QR mode to avoid confusions in my code. Thanks in advance.

**Comment by sidx1024** [comment]
@SumukhaK As of now there's no switch to disable the QR mode of payment. It is visible to non-mobile devices such as tablet and is dependent on screen resolution. The device you're testing might be on a custom DPI setting which increases the device's width (which is then detected as tablet).
