### ISSUE TITLE
UPI Payments not working

### ISSUE THREAD

**Issue by Ramachandran322** [razorpay/razorpay-android-sample-app#110]
Hello, 

I am using the latest razor pay sdk for my mobile app. The integration part was successful. However, I am facing few problems in the transaction while testing in Test Mode. 

1. UPI payments were not working but receiving order id, razor pay id, signature in onPaymentSuccess() callback.
2. I can save one particular card detail multiple times. There is no validation.
3. Also, I have an option to skip OTP validation.

Please someone help me with the above issues.

**Comment by sumedht** [comment]
Hi @Ramachandran322 
1. Can u elaborate more on what exactly not working in UPI?
2. Will check with this
3. Can u provide more details on this?

**Comment by vikasAgatsa** [comment]
Same problem here. I am not able to get to the Payment Successful intent. It is showing waiting for Payment Confirmation.

**Comment by ashiuniyal** [comment]
Yes, same prolem with upi payments, not getting response from razorpay on either success or failure functions.
amount is getting debited from account but no response.

**Comment by vikasAgatsa** [comment]
Hi @ashiuniyal, Please update to the latest version 

`implementation 'com.razorpay:checkout:1.5.12'`

in order to complete the payment via UPI.

**Comment by ashiuniyal** [comment]
Thanks @vikasAgatsa wiil check it

**Comment by MaheshVishnu** [comment]
@ashiuniyal Did you get the solution for this problem

**Comment by sumedht** [comment]
@Ramachandran322 @ashiuniyal @MaheshVishnu Hope this issue is fixed now.

**Comment by mehuljindal18** [comment]
does the UPI flow pass on an Intent to other apps or does it itself open a upi app wrapper of sorts

**Comment by imsudhirsingh** [comment]
Hi All,
Same problem i am facing , transaction done successfully but i am getting payment cancelled by user response . I am not able to get to the Payment Successful intent

All expert could you please help .

I am just using UPI integration with my android studio.

**Comment by Dhamu143** [comment]
I am also facing the same issue, I have integrated Razorpay in Angular/Node . Its working fine with cards transactions but not working with UPI integration

**Comment by SaurabhGaddelpalliwar** [comment]
For UPI ,
  final Checkout co = new Checkout();
 JSONObject options = new JSONObject();
options.put("payment_capture", "1"); // add this line in your json  (payment_capture is always default 0) for UPI it should be 1.

 co.open(activity, options);

**Comment by sumedht** [comment]
Closing this issue due to no further communication. Please feel free to either re-open the issue or create a new issue if you have any additional queries.

**Comment by thisshri** [comment]
For Razorpay web integration, the success handler callback is not being called when the payment is made through UPI.
In test mode in local, it works, but on production, it's not working. 
The payment is done and with status as authorized, but since the success handler is not called, I cannot process the order and capture the payment from the backend.

**Comment by ayush-razorpay** [comment]
@thisshri  please raise an Integrations ticket for this from your dashboard. We will look into this.

**Comment by Ankitathemil** [comment]
Using Razorpay Integration in Android, Every Mode of Payment works except UPI Intent, whenever user selects upi app the app opens with the upi receivers VPA being razorpay@icici after UPI Pin submission the UPI app throws error " Payment Failed due to Technical..." & the customer is thrown back to the source app.
In Razorpay dashboard the failed payment is logged as " User Cancelled" but in reality the customer did try to complete the payment.

Raised many queries with Razorpay, Every time they close the query or ask me to wait for 20-25 days for assigning UPI Terminal, Its been 3 Months. Still Going Back & Forth but not providing Solution, now 23 working days have passed since last they asked me to wait for 20-25 days, but still no solution.

**Comment by iamrahulck** [comment]
@thisshri I am facing the same issue. Whenever my customer pays through UPI, (most of the time) the success handler is not called and hence the order at my website is not processed though the user has already paid for it. So if you got any solutions, could you please help?

**Comment by DezyNation** [comment]
Is there any update on this issue?
I'm using NextJS 13 and have integrated Razorpay like this

```
const initializeRazorpay = () => {
    return new Promise((resolve) => {
      const script = document.createElement("script");
      script.src = "https://checkout.razorpay.com/v2/checkout.js";

      script.onload = () => {
        resolve(true);
      };
      script.onerror = (err) => {
        resolve(false);
        handleError(err, "Err while loading Razorpay");
      };

      document.body.appendChild(script);
    });
  };
  
  const payWithRazorpay = async ({
    amount,
    description,
    user,
    onSuccess,
    onFail,
  }) => {
    const res = await initializeRazorpay();

    if (!res) {
      alert("Razorpay SDK Failed to load");
      return;
    }

    // Make API call to the serverless API
    const data = await fetch(
      `${process.env.NEXT_PUBLIC_FRONTEND_URL}/api/razorpay`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          amount: amount,
        }),
      }
    ).then((t) => {
      console.log(t);
      return t.json();
    });

    var options = {
      key: process.env.NEXT_PUBLIC_RAZORPAY_KEY,
      name: "Virolife Foundation",
      currency: data.currency,
      amount: data.amount,
      order_id: data.id,
      description: description || "Thankyou for using Virolife",
      image: "https://avatars.githubusercontent.com/u/7713209?s=280&v=4",
      handler: function (response) {
        if (response.razorpay_payment_id) {
          onSuccess(response.razorpay_payment_id);
        } else {
          onFail();
        }
      },
      prefill: {
        name: user?.name || localStorage?.getItem("userName"),
        email: user?.email || localStorage?.getItem("email"),
      },
    };

    const paymentObject = new window.Razorpay(options);
    paymentObject.open();
};
```

Money is getting debited but the payment screen is always stuck to loading.

**Comment by vivekshindhe** [comment]
@DezyNation Is the end-product bundled into a native application(android), or is it running on chrome? Based on the implementation the answer for this may vary. For easier resolution, please create a ticket on your Razorpay Dashboard so we can get all the necessary details without much back & forth. Thanks.

**Comment by piyush-ramnani** [comment]
UPI mode would not be available unless you see 'Payment Methods' tab on your dashboard in 'Account and settings' option on the right. And that is available after submitting your KYC details. You don't have to wait for it to be verified, but need to complete it and 'Payment Methods' tab will be available. After that refresh your app and UPI option will show up.

**Comment by YuvaSriSai18** [comment]
I had a problem with Razorpay payment method
Currently I integrated Razorpay in my app but it is not showing UPI Payment method except that it is showing all the payment methods.

**Comment by padeepz** [comment]
same here, it is showing all payment in web , but not showing upi in mobile. i even raised several ticket in support, but they are closing it without any resolution or reply. 
in my dashboard-->accounts and setting---> UPI it is shown as activated 
i think they are hiding some regulatory issue by not enabling upi in mobiles and not informing to customers
