### ISSUE TITLE
onPaymentSuccess executed even user cancelled the process.

### ISSUE THREAD

**Issue by sandeepkumarmishra354** [razorpay/razorpay-android-sample-app#111]
Every time user cancel the wallet or upi methods the onPaymentSuccess function executed..
With other payment methods it works perfectly

**Comment by pronav** [comment]
Are you in test mode? onPaymentSuccess will be called on user cancel if payment becomes successful before user cancels the payment. This is a rare scenario, however in UPI test mode all payments are automatically successful in a very short span, which is how this could've been happening.

**Comment by sandeepkumarmishra354** [comment]
So in live mode my problem will be solved....?

**Comment by pronav** [comment]
Of course. As I said, if a user successfully completes payment and immediately cancels it, it'll still register as success.

In UPI test mode, you can't cancel most of the time because we've mocked payments to be successful very quickly (1-2s) except when VPA of `failure@razorpay` is used.

**Comment by sandeepkumarmishra354** [comment]
Thanks
