### ISSUE TITLE
In android after testing/production build checkout form is not opening in mobile.

### ISSUE THREAD

**Issue by abinash012** [razorpay/razorpay-android-sample-app#116]
when I am running locally through "ionic Cordova run browser" command, it is working fine. But after testing/production build it is not working. The problem is Razorpay page itself not coming after clicking on the "pay" button. Please help me to solve this issue.

**Comment by sumedht** [comment]
@abinash012 Does it give any error log for that? Can u plz share if there is any?
Also, have u tried our Cordova sample app?
https://github.com/razorpay/razorpay-cordova-sample-app

**Comment by sumedht** [comment]
@abinash012 Is it working now? can u update here?

**Comment by abinash012** [comment]
Now it's working fine sir. Issue was in build I think. Bcz that plugin was
not fetching while building application. Now it's proper.
