### ISSUE TITLE
How can I get razorpay_signature?

### ISSUE THREAD

**Issue by andev009** [razorpay/razorpay-android-sample-app#118]
After pay success,The callback only returns razorpayPaymentID.
	@Override
  public void onPaymentSuccess(String razorpayPaymentID) {
		/**
     * Add your logic here for a successful payment response
     */
  }
But need send razorpay_signature to validate, where can i get razorpay_signature?

**Comment by sagarnayak** [comment]
you need to implement
`com.razorpay.PaymentResultWithDataListener`
the methods to override are -
`    override fun onPaymentError(p0: Int, p1: String?, p2: PaymentData?) {
        showMessageInDialog(p1 ?: "Payment error")
    }

    override fun onPaymentSuccess(p0: String?, p1: PaymentData?) {
        logUtil.logV(p1?.paymentId ?: "payment id")
        logUtil.logV(p1?.signature ?: "signature id")
        logUtil.logV(p1?.orderId ?: "order id")
    }`
