### ISSUE TITLE
Whose details need to used in JSON OBJECT ? 

### ISSUE THREAD

**Issue by androidmads** [razorpay/razorpay-android-sample-app#12]
Merchant's detail or Customer's Detail 

JSONObject options = new JSONObject("{" +
                    "description: 'Demoing Charges'," +
                    "image: 'https://rzp-mobile.s3.amazonaws.com/images/rzp.png'," +
                    "currency: 'INR'}"
            );

            options.put("amount", "100");
            options.put("name", "Razorpay Corp");
            options.put("prefill", new JSONObject("{email: 'sm@razorpay.com', contact: '9876543210'}"));

            co.open(activity, options);

**Comment by captn3m0** [comment]
These will be the customer details. These details are used to prefill the checkout form, which customer has to fill.
