### ISSUE TITLE
Unable to start activity ComponentInfo...

### ISSUE THREAD

**Issue by manish8954776709** [razorpay/razorpay-android-sample-app#124]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.orra.android/com.razorpay.CheckoutActivity}: java.lang.RuntimeException: java.lang.IllegalAccessException: Class java.lang.Class<d.j.eb> cannot access  method java.io.InputStream com.razorpay.O__Y_.G__G_(java.io.InputStream, int, short) of class java.lang.Class<com.razorpay.O__Y_>

     Caused by: java.lang.RuntimeException: java.lang.IllegalAccessException: Class java.lang.Class<d.j.eb> cannot access  method java.io.InputStream com.razorpay.O__Y_.G__G_(java.io.InputStream, int, short) of class java.lang.Class<com.razorpay.O__Y_>

**Comment by sumedht** [comment]
@manish8954776709 Have u added proguard rules if u using proguard in u r application?
also what version of SDK you are using?

**Comment by akshaystreak** [comment]
Refer this
https://stackoverflow.com/questions/58706014/razorpay-crashes-on-payment-page-didnt-find-class-com-razorpay-d-1-in-flut
