### ISSUE TITLE
how to Create an Order  in android side ...

### ISSUE THREAD

**Issue by abhishek8506** [razorpay/razorpay-android-sample-app#130]
Any Help please.

**Comment by chitra-bahadur** [comment]
their are two ways for that either create api and call that api, second is implementing the java sdk of razor pay

**Comment by chitra-bahadur** [comment]
@abhishek8506  their are two ways to do that first is create an api and second is using razor pay java sdk. Java Sdk has some issue with pro-guard so creating api would be better options.
