### ISSUE TITLE
Gradle Sync Error

### ISSUE THREAD

**Issue by surapuramakhil** [razorpay/razorpay-android-sample-app#132]
ERROR: Failed to resolve: :razorpay-amazonpay-debug:
Affected Modules: app

**Comment by Mayur-Wadpalliwar** [comment]
@surapuramakhil You may remove the following from the build.gradle file under app and it shall work,

```
implementation 'com.android.support:customtabs:28.0.0'
    implementation(name: 'razorpay-amazonpay-debug', ext: 'aar')
    implementation(name: 'PayWithAmazon', ext: 'aar')
```

**Comment by surapuramakhil** [comment]
then how about Amazon pay?
can you make commit in master removing those lines from the master branch
