### ISSUE TITLE
Adding API key at runtime or in some other obfuscated method. 

### ISSUE THREAD

**Issue by sudeshim3** [razorpay/razorpay-android-sample-app#137]
**androidManifest.xml** contains live API key which is bad, how can we add it dynamically from a network request. the doc says 

**"API keys should not be hardcoded in the app. It should be sent from your server-side as app-related metadata fetch".**

How do we do this, can you provide the link to sample explaining how to do this.

**Comment by sumedht** [comment]
@sudeshim3 
There are ways to set an API key. 
1. Using Manifest (Not recommended as described in docs)
2. Using checkout's setKeyID("Public API Key"); method
in this case you can fetch API key from server call.

**Comment by sumedht** [comment]
@sudeshim3 Hopefully above comment has solved your issue.
for reference, u can find above link 
https://razorpay.com/docs/payment-gateway/android-integration/standard/#step-2---initialize-razorpay-android-standard-sdk
