### ISSUE TITLE
Toast or Dialog not displaying in onPaymentError method

### ISSUE THREAD

**Issue by sandeepmaaram** [razorpay/razorpay-android-sample-app#138]
When I am loading razorpay, after that I am manually pressing back button to test failure case. But here getting default toast with **method is throwing an error. Wrap the entire code of the method inside a try catch.** message and I want to display showing error dialog here, but it is not showing up. Event toast is also not coming.

Thanks in advance.

**Comment by sumedht** [comment]
@sandeepmaaram If u checked in the code,  there is onError(code, response) callback gets called in this case. If u want to customize the way error get shown, you can customize it there.
