### ISSUE TITLE
Error on success

### ISSUE THREAD

**Issue by 52280** [razorpay/razorpay-android-sample-app#139]
issue = Error:onPaymentError probably not implemented in your activity.

while integrating Razor pay fragment 

public class RepaymentFragment extends Fragment implements PaymentResultListener {

    private static final String TAG = RepaymentFragment.class.getSimpleName();

    TextView tv_id,tv_repayment,tv_loanAmount,tv_tenure,tv_dispersableAmount,tv_fee;
    TextView tv_feegst,tv_interestrate,tv_repaymentAmount;

    String id,repaymentdate,loanamount,tenure,dsAmount,fee,feegst,ir,ra;
    TextView tv_pay;
    private final String YOUR_KEY_ID = "rzp_test_xmfEfgsIpkOoTR";
    //final String public_key = String.valueOf("sdfsdfsdfsdf");

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        View view = inflater.inflate(R.layout.fragment_repayment, container, false);
        Checkout.preload(getActivity());

        tv_id = view.findViewById(R.id.customerid);
        tv_repayment = view.findViewById(R.id.loanrepaymentdate);
        tv_loanAmount = view.findViewById(R.id.finalloanAmount);
        tv_tenure = view.findViewById(R.id.finaltenure);
        tv_dispersableAmount = view.findViewById(R.id.DispersableAmount);
        tv_fee = view.findViewById(R.id.processingfee);
        tv_feegst = view.findViewById(R.id.Gstprocessingfee);
        tv_interestrate = view.findViewById(R.id.totalinterestrate);
        tv_repaymentAmount = view.findViewById(R.id.totalpayment);

      /*  id = getIntent().getStringExtra("userid");
        repaymentdate = getIntent().getStringExtra("loanUpdatetime");
        loanamount = getIntent().getStringExtra("payableAmount");
        tenure = getIntent().getStringExtra("loanduration");
        dsAmount = getIntent().getStringExtra("loanAmount");
        fee = getIntent().getStringExtra("processingfee");
        feegst = getIntent().getStringExtra("gst");
        ir = getIntent().getStringExtra("InteresRate");
        ra = getIntent().getStringExtra("payableAmount");
*/
        tv_pay = view.findViewById(R.id.repayment);
        tv_pay.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                startPayment();
            }
        });
        return view;
    }
    public void startPayment() {

        final RepaymentFragment repaymentFragment = this;

        Checkout checkout = new Checkout();
        checkout.setKeyID("rzp_test_xmfEfgsIpkOoTR");
        //checkout.setImage(R.drawable.logo);

         try {
             JSONObject options = new JSONObject();
         options.put("name", "Merchant Name");
         options.put("description", "123456");
         options.put("image", "https://s3.amazonaws.com/rzp-mobile/images/rzp.png");
         options.put("order_id", "9A33XWu170gUtm");
         options.put("currency", "INR");
         options.put("amount", "500");

         JSONObject prefill = new JSONObject();
         prefill.put("email","appsbuilder941@gmail.com");
         prefill.put("name","vijay");
         options.put("prefil",prefill);

         checkout.open(getActivity(),options);
         }
         catch(Exception e) {

             Log.e(TAG, "Error in starting Razorpay Checkout", e);
             //Toast.makeText(getActivity(),"Error in payment"+e.getMessage(),Toast.LENGTH_LONG).show();
         }
    }

    @Override
    public void onPaymentSuccess(String s) {
        try {
            Toast.makeText(getActivity(),"sucess",Toast.LENGTH_LONG).show();
        }catch (Exception e){
            Log.e(TAG, "Exception in onPaymentSuccess", e);
        }

    }

    @Override
    public void onPaymentError(int i, String s) {

        //Toast.makeText(getActivity(),"failed",Toast.LENGTH_LONG).show();

        try {
            
            Toast.makeText(getActivity(), "Payment failed: "+i+""+s,Toast.LENGTH_SHORT).show();
        } catch (Exception e) {
            Log.e(TAG, "Exception in onPaymentError", e);
        }
    }
}

**Comment by sumedht** [comment]
@52280 Can u elaborate issue?

**Comment by sumedht** [comment]
@52280 Closing this as there is no further communication
