### ISSUE TITLE
App Terminated when Open Payment Gateway on release mode. Working Perfect on debug mode

### ISSUE THREAD

**Issue by Lokeswara-betha** [razorpay/razorpay-android-sample-app#145]
This problem with solution is mentioned already in issue #42

However the solution didn't work for me.

App works fine (even without proguard rules) with flutter run --release but once we build apk & run the app, it didn't work

here is build gradle
`
buildTypes {
        release {            
            signingConfig signingConfigs.release
            //shrinkResources true
            //minifyEnabled true
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'),  'proguard-rules.pro' 
        }
    }`
Here is the Proguard rules

`-keepclassmembers class * {
@android.webkit.JavascriptInterface ;
}
-keepattributes JavascriptInterface
-keepattributes Annotation
-dontwarn com.razorpay.**
-keep class com.razorpay.** {;}
-optimizations !method/inlining/
-keepclasseswithmembers class * {
public void onPayment*(...);
}`

**Comment by vivekshindhe** [comment]
@Lokeswara-betha can we get the crash-logs for the same so that it helps us analyze the issue?

**Comment by sumedht** [comment]
@Lokeswara-betha Still facing same issue?

**Comment by Lokeswara-betha** [comment]
Nope , It was resolved.

**Comment by gouthamravella** [comment]
How this issue was resolved?
