### ISSUE TITLE
App Crashing In Checkout SDK In Android Studio Version 3.6.1 And Gradle Version 5.6.4

### ISSUE THREAD

**Issue by exaltaenergy** [razorpay/razorpay-android-sample-app#148]
App Crashing In Checkout SDK In Android Studio Version 3.6.1 And Gradle Version 5.6.4
Please Share Your SDK jar zip file with support file i will debug it of slandered sdk.

**Comment by sumedht** [comment]
can u share more details such as crash log to have more inputs on this.

**Comment by sumedht** [comment]
@exaltaenergy Have any more details?

**Comment by sumedht** [comment]
Closing this issue due to no response from your side. Please feel free to either re-open the issue or create a new issue if you have any additional queries.
