### ISSUE TITLE
Android custom Integration - How to enable/disable payment mode?

### ISSUE THREAD

**Issue by sankar-gp** [razorpay/razorpay-android-sample-app#149]
Hello,

I need to disable/enable UPI, credit/debit cards, net banking and wallets whenever i need. How can i achieve it?

**Comment by anwernuman** [comment]
You will have to pass the method parameter and then pass all the available option as true or false.
Will only work if contact and email are also pre-filled. 
Possible values:● card● netbanking● wallet● emi● upi.

To know more about it you can follow the thread here. 
https://razorpay.com/docs/payment-gateway/web-integration/standard/checkout-form/

**Comment by sankar-gp** [comment]
@anwernuman I need to know how to do it in android app side

**Comment by sumedht** [comment]
@sankar-gp U can find details here.
https://razorpay.com/docs/payment-gateway/android-integration/standard/
Let us know if something else is required.
