### ISSUE TITLE
Payment "failure" callback Android standard sdk integration in test mode

### ISSUE THREAD

**Issue by sandeepmaaram** [razorpay/razorpay-android-sample-app#152]
Summary is given below (Integrated Android SDK 1.5.16)

`implementation 'com.razorpay:checkout:1.5.16'`

We integrated android standard sdk integration. In test mode after payment is completed we are clicking "**Failure**" option

**Expected :** When user press on **failure**, it should redirect to application i.e callback method in respective activity

**Actual :** When user press on failure, it should take the user to payment failed screen with retry button.

Here requirement issue simple, after pressing failure button, it should back to app and call and respective callback instead of retry option. 

For your information, please find below images.

![WhatsApp Image 2020-03-27 at 10 48 12 AM](https://user-images.githubusercontent.com/3026857/77829427-f7aabd00-7147-11ea-8569-70dc108d9eff.jpeg)
![WhatsApp Image 2020-03-27 at 10 44 39 AM](https://user-images.githubusercontent.com/3026857/77829434-fed1cb00-7147-11ea-9a70-53420f33c232.jpeg)

Thanks.

**Comment by sumedht** [comment]
@sandeepmaaram Can u share what payload you are passing to SDK. It is possible that u passing 
`retry = true` and because of that it's shows retry option on failure.

**Comment by sandeepmaaram** [comment]
Yes `retry = true` property resolved the issue. 
Thanks

**Comment by RCuztomise** [comment]
How i can set the payload?

**Comment by karun02525** [comment]
> retry = true

not working

**Comment by sumedht** [comment]
@karun02525 can u plz elaborate more on this? It will help us to understand ur query & we can help u out in that

**Comment by karun02525** [comment]
Hi,
I am trying to implement android razorpay sdk everything is success but i am fecing failures response it not call errors methods.

I'm useing callback interface with PaymentResultWithDataListener instead of PaymentResultListener.

Please update me quickly.

**Comment by sumedht** [comment]
@karun02525 Have u checked with sample app code? does callback listeners not getting triggered?

**Comment by karun02525** [comment]
> @karun02525 Have u checked with sample app code? does callback listeners not getting triggered?

I have already checked everything success method called but failure method not call

**Comment by vivekshindhe** [comment]
@karun02525 If possible can you create a sample project where you can reproduce this issue so we could look at it? We've never had this issue. This will help us look into this in a detailed manner.
