### ISSUE TITLE
Customer payment not allowed for the subscription at this stage

### ISSUE THREAD

**Issue by mbchandar** [razorpay/razorpay-android-sample-app#154]
I am getting this issue

Trying to use Subscription with checkout as per doc https://razorpay.com/docs/subscriptions/api/#subscription-via-checkout

Error message
Customer payment not allowed for the subscription at this stage

public void startPayment() {
        /*
          You need to pass current activity in order to let Razorpay create CheckoutActivity
         */
        final Activity activity = this;

        final Checkout co = new Checkout();

        try {
            JSONObject options = new JSONObject();
            options.put("name", "Razorpay Corp");
            options.put("subscription_id", "sub_Eg24Wgcro4OLax");

            options.put("description", "Demoing Charges");
            //You can omit the image option to fetch the image from dashboard
            options.put("image", "https://s3.amazonaws.com/rzp-mobile/images/rzp.png");
            options.put("currency", "INR");
            options.put("amount", "100");

            JSONObject preFill = new JSONObject();
            preFill.put("email", "test@razorpay.com");
            preFill.put("contact", "9876543210");

            options.put("prefill", preFill);

            co.open(activity, options);
        } catch (Exception e) {
            Toast.makeText(activity, "Error in payment: " + e.getMessage(), Toast.LENGTH_SHORT)
                    .show();
            e.printStackTrace();
        }
    }

**Comment by shreyassridhar1** [comment]
@mbchandar while creating the subscription, the "total_count" parameter should be more than '1'. Subscriptions is a recurring payment functionality and the value for the parameter "total_count" should always be more than 1. This parameter specifies the number of billing cycles you want your subscription to be active for. For eg: If you have created a monthly plan and your total_count parameter is 3, then the subscription cycle will go on for 3 months and the payment will be deducted at the end of each month for 3 months.

**Comment by mbchandar** [comment]
your error message does not specify that. also how i do setup to have 1 month subscription only that means total_count should be 1 only right?

**Comment by shreyassridhar1** [comment]
@mbchandar Sir, if you want a 1 time payment for a 1 month subscription, then there is no use of using the subscriptions product. You might as well just use any of the other payment accepting products. Subscriptions are used when the merchant wants to accept payments automatically over a period of time. 

You can create a weekly plan and accept payments per week for 1 month. Even there the total_count will be more than 1.

**Comment by mbchandar** [comment]
hello, i want to setup a trial period of 1 month with a basic amount. does your product support it?

**Comment by shreyassridhar1** [comment]
Subscriptions cannot be sent for 1 month. You can start a subscription for more than 1 month and after the first month delete the subscription. This is a workaround/hack

**Comment by mbchandar** [comment]
so razorpay subscription does not support setting up of trial period of 1 month ?

**Comment by shreyassridhar1** [comment]
You could set up a trial period by assigning a date for 1 month later to the 'subscription_start_at' parameter, and the billing will start from the second month onwards.

**Comment by mbchandar** [comment]
i had updated with total count as 2 and able to create subscription. but unable to make payment using test card given by razorpay for subscription. gettting payment failed. is there a sample app for subscription ?

**Comment by mbchandar** [comment]
it succeeded finally in web. not in app. how to setup to collect money upfront starting today?

**Comment by shreyassridhar1** [comment]
If you want to start the subscription starting from today then dont pass the subscription_start_at parameter. The subscription will start immediately and take the 1st billing cycle payment.

**Comment by sumedht** [comment]
Closing this issue due to no further communication. Please feel free to either re-open the issue or create a new issue if you have any additional queries.

**Comment by ServeMyTable** [comment]
> @mbchandar while creating the subscription, the "total_count" parameter should be more than '1'. Subscriptions is a recurring payment functionality and the value for the parameter "total_count" should always be more than 1. This parameter specifies the number of billing cycles you want your subscription to be active for. For eg: If you have created a monthly plan and your total_count parameter is 3, then the subscription cycle will go on for 3 months and the payment will be deducted at the end of each month for 3 months.

Then we need to create subscription each time we are out of total_count ?

**Comment by sanjeet007** [comment]
Customer payment not allowed for the subscription at this stage 
Payment failed:: {"code":"BAD_REQUEST_ERROR","description":"Customer payment not allowed for the subscription at this stage.","source":"NA","step":"NA","reason":"NA","metadata":{}} ::null

**Comment by vivekshindhe** [comment]
@sanjeet007 Could you please send the payload you are using? Also, please ensure total_count does not equal to 1.

**Comment by sanjeet007** [comment]
> @sanjeet007 Could you please send the payload you are using? Also, please ensure total_count does not equal to 1.

final Activity activity = this;

            Checkout checkout = new Checkout();

            try {
                JSONObject options = new JSONObject();
                options.put("name",PRODUCT_NAME));
                options.put("description", PRODUCT_NAME));
                options.put("image", "jpg");
                if (orderID != null && !isPlanMode) {
                    options.put("order_id", orderID);
                }
                options.put("theme.color", "#009c95");
                options.put("currency", "INR");
                if (subSubscriptionID != null && isPlanMode) {
                    options.put("subscription_id", subSubscriptionID);
                    options.put("recurring", true);
                }
                options.put("prefill.email", PrefUtils.getFromPrefs(this, PrefUtils.EMAIL));
                options.put("prefill.contact", PrefUtils.getFromPrefs(this, PrefUtils.MOBILE));    
                checkout.open(activity, options);

            } catch (Exception e) {
                //Toast.makeText(activity, "Error in payment: " + e.getMessage(), Toast.LENGTH_SHORT).show();
                Log.e("error :", e.getMessage());
                e.printStackTrace();
            }

**Comment by sanjeet007** [comment]
> total_count

What is this total_count key for what we managing and where ?

**Comment by sanjeet007** [comment]
and do we need to create a different subscription_id for ever user for same plan ex: like I have one plan and I generate subscripton_id from backend then the plan_id would be same for all user if anyone click I will get subscrption_id that will be same for all or any other thing happening here
