### ISSUE TITLE
1. Go to   **flutterSdk folder->.pub-cache->hosted->pub.dartlang.org-> razorpay_flutter-1.1.4->android**

### ISSUE THREAD

**Issue by Selvam-bestea** [razorpay/razorpay-android-sample-app#160]
1. Go to   **flutterSdk folder->.pub-cache->hosted->pub.dartlang.org upto this folder i can able to navigate but > razorpay_flutter-1.1.4->android** this not available

**Comment by sumedht** [comment]
@Selvam-bestea We have updated to latest version of Flutter SDK version. Please do check https://github.com/razorpay/razorpay-flutter
