### ISSUE TITLE
Callback methods are not invoked with UPI Payment in background

### ISSUE THREAD

**Issue by Sandeepbandral** [razorpay/razorpay-android-sample-app#161]
When I make payment from my Android app with UPI, I have to visit the UPI app to complete the payment but after completion of payment the call back methods are not invoked in background.

Call back methods are invoked only when activity comes in foreground. How do I make it work even when activity is in background?

I would really appreciate any help here.

**Comment by sumedht** [comment]
@Sandeepbandral PSP apps give callback in **onActivityResult()** method so it will come when activity is in foreground.
