### ISSUE TITLE
Razorpay Not working in fragments.

### ISSUE THREAD

**Issue by Spikeysanju** [razorpay/razorpay-android-sample-app#162]

**Comment by anfaas1618** [comment]
can you log the error here ?

**Comment by sunil456** [comment]
I am gating this error

W/cr_media: Requires BLUETOOTH permission
W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
I/Choreographer: Skipped 44 frames!  The application may be doing too much work on its main thread.
I/OpenGLRenderer: Davey! duration=857ms; Flags=1, IntendedVsync=71507935886419, Vsync=71508669219723, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=71508684962445, AnimationStart=71508685170883, PerformTraversalsStart=71508686588696, DrawStart=71508745970316, SyncQueued=71508750772087, SyncStart=71508751209119, IssueDrawCommandsStart=71508751329171, SwapBuffers=71508791584748, FrameCompleted=71508793594279, DequeueBufferDuration=146000, QueueBufferDuration=1275000, 
I/OpenGLRenderer: Davey! duration=867ms; Flags=1, IntendedVsync=71507935886419, Vsync=71508669219723, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=71508684962445, AnimationStart=71508685170883, PerformTraversalsStart=71508686588696, DrawStart=71508795072769, SyncQueued=71508798899800, SyncStart=71508799263030, IssueDrawCommandsStart=71508799474436, SwapBuffers=71508802638395, FrameCompleted=71508803630218, DequeueBufferDuration=576000, QueueBufferDuration=324000, 
D/skia: --- Failed to create image decoder with message 'unimplemented'
W/entsystem.mitr: resources.arsc in APK '/data/app/com.lenovo.anyshare.gps-1Lkdiu2KUIrVbKb1i11hKw==/base.apk' is compressed.
D/skia: --- Failed to create image decoder with message 'unimplemented'
D/skia: --- Failed to create image decoder with message 'unimplemented'

**Comment by anfaas1618** [comment]
try to add bluetooth permission

**Comment by sunil456** [comment]
But why you need Bluetooth permission

**Comment by anfaas1618** [comment]
ok so you have not added anything else in code ie it is same as master ??

**Comment by sunil456** [comment]
yes sir

**Comment by sunil456** [comment]
Hi,
I am facing an issue during payment. I multiply payment amount by 100
(1000*100) as shown in tutorials given by razor team
but it's not working. let suppose i have to pay 1000 but when it goes to
razor pay it shown m 100 can you please help to resolve this

           JSONObject options = new JSONObject();
            options.put("name", customerName);
            options.put("description", "");
            options.put("image",
"https://s3.amazonaws.com/rzp-mobile/images/rzp.png");
            options.put("order_id", razorPayOrderID);
            options.put("currency", currency);

            //amount is in paisa so we have to convert it to rupees
//            paymentAmount = paymentAmount*100;
            options.put("amount", paymentAmount*100);
            JSONObject preFile = new JSONObject();
            preFile.put("email", customerEmail);
            preFile.put("contact", customerMobileNumber);
            options.put("prefill", preFile);
            checkout.open(activity, options);
