### ISSUE TITLE
Razor payment not working on fragment

### ISSUE THREAD

**Issue by sunil456** [razorpay/razorpay-android-sample-app#166]
W/entsystem.mitr: Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
W/cr_media: Requires BLUETOOTH permission
W/VideoCapabilities: Unrecognized profile/level 0/3 for video/mpeg2
I/Choreographer: Skipped 44 frames!  The application may be doing too much work on its main thread.
I/OpenGLRenderer: Davey! duration=857ms; Flags=1, IntendedVsync=71507935886419, Vsync=71508669219723, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=71508684962445, AnimationStart=71508685170883, PerformTraversalsStart=71508686588696, DrawStart=71508745970316, SyncQueued=71508750772087, SyncStart=71508751209119, IssueDrawCommandsStart=71508751329171, SwapBuffers=71508791584748, FrameCompleted=71508793594279, DequeueBufferDuration=146000, QueueBufferDuration=1275000, 
I/OpenGLRenderer: Davey! duration=867ms; Flags=1, IntendedVsync=71507935886419, Vsync=71508669219723, OldestInputEvent=9223372036854775807, NewestInputEvent=0, HandleInputStart=71508684962445, AnimationStart=71508685170883, PerformTraversalsStart=71508686588696, DrawStart=71508795072769, SyncQueued=71508798899800, SyncStart=71508799263030, IssueDrawCommandsStart=71508799474436, SwapBuffers=71508802638395, FrameCompleted=71508803630218, DequeueBufferDuration=576000, QueueBufferDuration=324000, 
D/skia: --- Failed to create image decoder with message 'unimplemented'
W/entsystem.mitr: resources.arsc in APK '/data/app/com.lenovo.anyshare.gps-1Lkdiu2KUIrVbKb1i11hKw==/base.apk' is compressed.
D/skia: --- Failed to create image decoder with message 'unimplemented'
D/skia: --- Failed to create image decoder with message 'unimplemented'
E/chromium: [ERROR:aw_browser_terminator.cc(125)] Renderer process (27558) crash detected (code -1).

**Comment by sayusharma** [comment]
Its an ongoing bug from razor pay side in their latest sdk version. Please downgrade your razorpay sdk version.

**Comment by vivekshindhe** [comment]
@sunil456 Can you please explain what you are trying to achieve and what it means when you say it's not working? The logs don't have anything related to razorpay. So understanding what you want to achieve here will help us to resolve this issue.

**Comment by sumedht** [comment]
@sunil456 @sayusharma Any update on this?

**Comment by sunil456** [comment]
#sumedht 

> 
> 
> @sunil456 @sayusharma Any update on this?

No But u you can use interface for calling razor pay in your fragment.

**Comment by sumedht** [comment]
Closing this issue due to no further communication. Please feel free to either re-open the issue or create a new issue if you have any additional queries.
