### ISSUE TITLE
Custom Payment not descriptive

### ISSUE THREAD

**Issue by rahuldange09** [razorpay/razorpay-android-sample-app#169]
Hello, We are implementing razorpay's custom payment SDK. As we were going through the docs of it, on first page of android custom SDK integration, we came across this line.

> The sample AndroidManifest.xml file with auto-OTP reading feature enabled is shown below:

As this says auto otp reading feature. This feature for what? Which OTP you talking about and also the manifest's code below this line doesn't have that otp permission line. 
We thought it is for netbanking or card payment's bank page OTP auto reading feature but even after adding sms permission (which in custom sample app of android), It doesn't auto read OTP.

Can you guys please help us out with this. Are we missing here something or misunderstood.
Please let us know.

**Comment by vivekshindhe** [comment]
@rahuldange09 Glad, you reached out to us. Razorpay SDKs use two types of SMS retrieval options. One, the SMS_PERMISSIONS in the manifest file. Second, the SMS_RETRIEVER APIs provided by Google, in case the merchant doesn't want to use the global permissions as Play Store is coming down on it. You can use either. And it is only for netbanking right now. Working to bring it to Card transactions and well. 
Also, just including in the manifest won't work. You will have to ask for permission in the app and the SDK will pick it up from there based on the result of the permission. 
Will try to make the document a bit more detailed on this front. Thanks for pointing this out.

**Comment by rahuldange09** [comment]
@vivekshindhe Thank you for the reply.
Until you update the document, can you please give us steps here to achieve auto OTP reading feature. As our customers are facing this we want to fix it as soon as possible.

**Comment by vivekshindhe** [comment]
@rahuldange09 sure thing. Could please let us know the SDK version of the Razorpay SDK you are using currently?

**Comment by rahuldange09** [comment]
@vivekshindhe Latest one which is mentioned in your custom SDK docs. v3.8.10

**Comment by vivekshindhe** [comment]
@rahuldange09 Hey, sorry for the late info. It turns out we are apparently disabling that feature for net banking due to many such reasons. You can safely remove the SMS permissions from your app for the same. Will be closing this ticket now. Let us know if you have any other issues with the integration. 
Thanks, 
Vivek Shindhe
