### ISSUE TITLE
Next button in email field

### ISSUE THREAD

**Issue by nareshkatta99** [razorpay/razorpay-android-sample-app#18]
After entering correct phone number and email, when I click on next button in key board, either key board should hide, or keyboard button should be "OK". Its annoying to press back button and clicking on payment option.
![device-2017-02-10-113201 edited](https://cloud.githubusercontent.com/assets/7877291/22816192/7b91193a-ef86-11e6-87a1-3b7145059327.png)

**Comment by gagandeep1984** [comment]
good catch!

**Comment by Naresh-Katta** [comment]
Any update?
