### ISSUE TITLE
I added this version of the SDK  implementation 'com.razorpay:checkout:1.6.3' and after uploading to Play Store i'm getting this message from Google Your app(s) are vulnerable to Intent Redirection.

### ISSUE THREAD

**Issue by cr7rahul** [razorpay/razorpay-android-sample-app#188]
## Description

Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest Razorpay Android SDK to make sure your issue has not already been fixed. 

## Razorpay SDK Version :
Open `build.gradle`. > Copy `com.razorpay` version here or github URL. 

## Android OS Version :
Any specific android version if this issue is only occuring on a specific version. 

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Code example, screenshot, or link to a repository:
Please provide a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by AYAN249** [comment]
Kindly upgrade to the latest version and integrate accordingly at your end.
https://mvnrepository.com/artifact/com.razorpay/checkout
