### ISSUE TITLE
com.razorpay:checkout:1.6.3  Flash back Bug and Other bug

### ISSUE THREAD

**Issue by 317056658** [razorpay/razorpay-android-sample-app#189]
Problem 1: The first time razorpay SDk is called to open the RazorPay interface (CheckoutActivity), and the second time, the interface (CheckoutActivity) is not affected normally.
Android Studio reported the following error:
Activity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.l_$w$$2@5d58d2f that was originally registered here. Are you missing a call to unregisterReceiver()?

Problem 2: Sometimes open razorPay (CheckoutActivity) with a black screen.
I used Mi 8 for testing. Could you tell me how to solve this problem?

**Comment by sumedht** [comment]
@317056658 we have fixed this issue in our latest v1.6.4 plz update to that version

**Comment by 317056658** [comment]
thanks  Handsome
