### ISSUE TITLE
Crash in razorpay sdk

### ISSUE THREAD

**Issue by milindbableshwar** [razorpay/razorpay-android-sample-app#19]
http://crashes.to/s/d52498350e4

Getting this crash quite frequently.

**Comment by hariramsvnit** [comment]
@milindbableshwar Thanks for reporting the crash. 

We will be releasing an update soon and that will fix this crash also.

**Comment by hariramsvnit** [comment]
@milindbableshwar This crash has been fixed in [v1.2.1](https://github.com/razorpay/razorpay-android-sample-app/releases/tag/v1.2.1)
