### ISSUE TITLE
1.5.16 -> IllegalArgumentException Service not registered: com.razorpay.AdvertisingIdUtil$R$$r_@3b75ed7

### ISSUE THREAD

**Issue by sambit-m** [razorpay/razorpay-android-sample-app#191]
## Description

Crash in production [Version **1.5.16**]:
 **IllegalArgumentException, Service not registered: com.razorpay.AdvertisingIdUtil$R$$r_@3b75ed7**

![image](https://user-images.githubusercontent.com/11912046/98352479-10ffda00-2044-11eb-8245-219ba9791521.png)

## Razorpay SDK Version :
com.razorpay:checkout:1.5.16

## Android OS Version :
realme 5pro, Android 10

It happened in production and only 1 event till now, kindly let me know if there's anything at my end to resolve this issue. Timestamp: Nov 4, 2020, 4:21:51 PM

**Comment by sumedht** [comment]
@sambit-m There was an issue with our older SDK which was not compatible with Android 10. Please update to the latest version of SDK 1.6.4

**Comment by sambit-m** [comment]
@sumedht yep I just saw it but seems like it's still in WIP. Please confirm once again to update.

**Comment by sumedht** [comment]
@sambit-m u can update to 1.6.4

**Comment by sambit-m** [comment]
@sumedht Please update the docs/changelogs with release tags and **gradle isn't even notifying the update**.
