### ISSUE TITLE
v 1.5.13 aar I am writing a binding library for Xamarin and running into the issue

### ISSUE THREAD

**Issue by gokulakshay** [razorpay/razorpay-android-sample-app#197]
window.getDeviceDetails is not a function

**Comment by sumedht** [comment]
@gokulakshay is this error ur getting while executing? can u plz provide more details on which lib version u wanted to create wrapper?

**Comment by vivekshindhe** [comment]
@gokulakshay Closing the issue due to inactivity. Please respond here or create a new issue in case you need more assistance.
