### ISSUE TITLE
getting a blink on screen

### ISSUE THREAD

**Issue by ravisharma46** [razorpay/razorpay-android-sample-app#200]
## Description

whenever i start a payment activity it gives me a blink. which is not a good experience for user. i am using  Checkout.preload(getApplicationContext()); in onCreate method.

## Razorpay SDK Version :
implementation 'com.razorpay:checkout:1.5.16'

## Android OS Version :
android 9

### What you did:

 i am opening a payment activity where i have a button for user to start a payment.
## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. open payment activity
2. a blink will occur

## Code example, screenshot, or link to a repository:
Please provide a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by vivekshindhe** [comment]
@ravisharma46 Hey, thanks for letting us know. The SDK has been upgraded to version '1.6.4'. Please try with that. If the issue still persists we'll take this ticket forward.

**Comment by ravisharma46** [comment]
after updating to version 1.6.4 still I am getting a blink on opening my payment activity. My payment activity extends to AppCompatActivity. 

Please look into this and resolve my issue asap. we have to rollout our app to production.

**Comment by vivekshindhe** [comment]
@ravisharma46 is it possible for you to share a video of the same please?

**Comment by ravisharma46** [comment]
https://drive.google.com/file/d/1O64a9ZzjoloYjkSvfx30Yb0SZSAeXpnx/view?usp=sharing

please see this video.

**Comment by vivekshindhe** [comment]
@ravisharma46 Saw the video. Is there a reason you concluded that this blink was due to razorpay?

**Comment by vivekshindhe** [comment]
is the issue that the PaymentActivity isn't loading?

**Comment by ravisharma46** [comment]
yes the blink was due to razorpay. I am using Checkout.preload(getApplicationContext()); in onCreate method. if i remove this i won't get a blink.

**Comment by ravisharma46** [comment]
everything is working fine only the isssue is that i got blink on opening payment activity.

**Comment by vivekshindhe** [comment]
you can try doing the preload before you initialize the views in this activity.

**Comment by ravisharma46** [comment]
i am still facing same issue. I have initialize preload before setContentView()

**Comment by JagadeeshDamarasingu** [comment]
I'm guessing, the issue is not a blink of screen, Its a crash.  @ravisharma46, If u can add Additional Logs, it would be helpful in analyzing the what's happening

**Comment by sumedht** [comment]
@ravisharma46 No need to call pre-load. U can follow the documentation where we are calling directly open method with checkout's object.
https://razorpay.com/docs/payment-gateway/android-integration/standard/

**Comment by ravisharma46** [comment]
ctivity com.razorpay.CheckoutActivity has leaked IntentReceiver com.razorpay.CheckoutPresenterImpl$1@c785044 that was originally registered here. Are you missing a call to unregisterReceiver()?
        

Can you explain this error. I am using 1.6.6 sdk version
