### ISSUE TITLE
Razorpay doesn't open PhonePe app in intent flow

### ISSUE THREAD

**Issue by sudeshim3** [razorpay/razorpay-android-sample-app#204]
## Description

I am integrating Razorpay custom SDK in android app, I have 3 payment methods. Google Pay, PhonePe and PayTm. Both Google pay and PayTm launch successfully with the intent flow. 
```val GOOGLE_PAY_PACKAGE_ID = com.google.android.apps.nbu.paisa.user```
and putting this ```put("upi_app_package_name", vpaOrPackageName)``` in payload opens google play perfectly.
However, if I try to do the same with phonePe 
```("upi_app_package_name", "com.phonePe.app")``` 
It doesn't launch the PhonePe app. I have the latest version of PhonePe installed on my device.

In the documentation, it is mentioned that PhonePe is supported https://razorpay.com/docs/payment-gateway/payment-methods/

## Razorpay SDK Version :
razorpay-android-3.8.7.aar

**Comment by sumedht** [comment]
@sudeshim3 can u plz try to pass `com.phonepe.app`. I think u passing `com.phonePe.app`

**Comment by sudeshim3** [comment]
@sumedht , No I tried changing it but it didn't help. Moreover If you notice in the app Id of phonepe its all smallcap https://play.google.com/store/apps/details?id=com.phonepe.app. 

Result:
![image](https://user-images.githubusercontent.com/34063388/106999274-e7be2980-67ab-11eb-9610-39e5e341c971.png)

I get the razorpay app chooser. And if you notice PhonePe app isn't shown in the apps list.

**Comment by sudeshim3** [comment]
```
JSONObject("{currency: 'INR'}").apply {
            put("amount",200)
            put("email", "users_email")
            put("_[flow]", "intent")
            put("upi_app_package_name","com.phonepe.app")
            put("display_logo", false)
            put("method", "upi")
```

If I pass `"net.one97.paytm"` Paytm app is launched successfully and If I pass "com.google.android.apps.nbu.paisa.user" Google pay is launched. However, phonepe doesn't open when app Id of phonepe is used.

**Comment by sudeshim3** [comment]
I checked the source code of file `BaseRazorpay.kt`
The function `getApppsWhichSpportUpi` checks for the deeplink. `upi://pay`. In such case, PhonePe wouldn't show up because It doesn't support the intent flow. I was assuming that Razorpay has a custom webview or it internally handles payment flow on behalf of PhonePe. If PhonePe is not supported kindly update the documentation. 

       public static List<ApplicationDetails> getAppsWhichSupportUpi(Context var0) {
        
        AnalyticsUtil.trackEvent(AnalyticsEvent.CUSTOM_UI_GET_APPS_SUPPORTING_UPI);
        HashSet var1 = Q_$2$(var0);
        List var2 = BaseUtils.getListOfAppsWhichHandleDeepLink(var0, "upi://pay");
        .....
      }

**Comment by sumedht** [comment]
@sudeshim3 PhonePe uses `upi://pay` only. It's not reflecting in a list because the app may not be linked to a bank account. PhonePe uses smart intent & that's why it's not reflecting in supported UPI app. 
To solve this, plz check device on which u r running app has PhonePe & linked to a bank account. If it's just installed & not linked to a bank account, It will not get shown.

**Comment by sudeshim3** [comment]
@sumedht , Yes it worked. I didn't link my UPI with a bank account in PhonePe and that's the reason it didn't show up.
 Didn't doubt this because HDFC Pay and Axis Mobile show UPI create flow. Now that's something to do with PhonePe specific flow. Thanks again.
