### ISSUE TITLE
PaymentResultListener

### ISSUE THREAD

**Issue by karun02525** [razorpay/razorpay-android-sample-app#206]
Hi,
I am trying to implement android Razorpay SDK everything is a success but I am fencing failures response it did not call errors methods.

I'm using a callback interface with PaymentResultWithDataListener instead of PaymentResultListener.

Please update me quickly. please help me urgent 8920828585

**Comment by sumedht** [comment]
@karun02525 can u elaborate more on 
`but I am fencing failures response it did not call errors methods.`

**Comment by KrishHari** [comment]
@sumedht facing the same issue. We are using version 1.6.6. After opening the Checkout page and then pressing back button getting Toast message "Your onPaymentError  method is throwing an error. Wrap the entire code of the method inside try catch"
We were getting the callback to onPaymentError in the 1.5.x versions.

**Comment by sumedht** [comment]
@KrishHari We have checked with our SDK & sample app. It's not reproduced. Have u faced this issue in some specific scenario? if possible can u share a video of it for better understanding. Also, u can share the payload ur passing?

**Comment by KrishHari** [comment]
@sumedht The issue is not reproduced on the sample app. Probable cause is because there is a fragment in our usecase. the payment is initiated from the fragment which opens the CheckoutActivity and on clicking back button, the parent activity which hosted the fragment is not receiving the onPaymentError call back. the same was working fine in your 1.5.X versions.

**Comment by vivekshindhe** [comment]
> @sumedht facing the same issue. We are using version 1.6.6. After opening the Checkout page and then pressing back button getting Toast message "Your onPaymentError method is throwing an error. Wrap the entire code of the method inside try catch"
> We were getting the callback to onPaymentError in the 1.5.x versions.

Can you send the code for onPaymentError here? @KrishHari

**Comment by rohit-337** [comment]
Make the second and third parameters nullable on the `onPaymentError` callback while you implement it. 
For eg: `override fun onPaymentError(errorCode: Int, errorMessage: String?, paymentData: PaymentData?) `

**Comment by vivekshindhe** [comment]
@karun02525 @KrishHari closing the thread due to inactivity. Please respond here or create a new issue in case this isn't fixed for you.
