### ISSUE TITLE
Segment Class with ASCII character's causes proguard error

### ISSUE THREAD

**Issue by vipulasri** [razorpay/razorpay-android-sample-app#21]
Razorpay `v1.0.2` and also tested on `v1.2.0` causes the error with Segment Class having ASCII character in class name while applying proguard.

Android gradle version: 2.3.0
Android Studio: 2.3

I am having this error: 
`Error:org.gradle.api.UncheckedIOException: java.io.IOException: Failed to read zip file 'app/build/intermediates/transforms/proguard/release/jars/3/1f/main.jar'.`

> Caused by: java.io.IOException: Failed to read stored entry 'com/razorpay/Segment$ۥ.class'.
> 	at com.android.apkzlib.zip.CentralDirectory.readEntry(CentralDirectory.java:367)
> 	at com.android.apkzlib.zip.CentralDirectory.makeFromData(CentralDirectory.java:225)
> 	... 36 more

**Comment by mb-14** [comment]
@vipulasri Make sure you're using the latest version of gradle. You can go through this page for instructions on updating gradle: https://developer.android.com/studio/releases/gradle-plugin.html#updating-gradle

**Comment by vipulasri** [comment]
@mb-14 I tried latest version too.

**Comment by mb-14** [comment]
@vipulasri Can you try using v2.2.0 of the Android Plugin for gradle?

**Comment by vipulasri** [comment]
@mb-14 with Android gradle plugin version `v2.2.0` and `v2.2.3` its working perfectly fine. But the problem is Android Studio 2.3 requires Android gradle plugin version `v2.3.0`. That's why its working. 
And to use Android gradle plugin version `v2.2.0` and `v2.2.3`will have to downgrade Android Studio.

**Comment by mb-14** [comment]
@vipulasri You don't need to downgrade Android Studio to use `v2.2.3`. You just need to change the plugin version in your `build.gradle` file.
Also, according this [thread](https://code.google.com/p/android/issues/detail?id=221057), the issue with non-ASCII characters should be fixed in the next version of the plugin.

**Comment by vipulasri** [comment]
@mb-14 I tried that but the thing is downgrading causes crashes with Animated Support Vector Library. And Yes, I read that [thread](https://code.google.com/p/android/issues/detail?id=221057) but I opened this issue so that if the problem lies with the ASCII character within your class name so that you can fix this issue in next release, which will help other people too with same configuration of android studio and android studio gradle plugin.

**Comment by sathishsr** [comment]
Is there any solution than downgrading the gradle versions?.It works only if I downgrade my gradle versions. But my other support library depends on it.

**Comment by mb-14** [comment]
@sathishsr @vipulasri We use dexguard for obfuscating our library which adds non-ASCII characters to our classes by default.
Will be excluding overriding this default behaviour to exclude non-ASCII characters for the next release.

**Comment by hariramsvnit** [comment]
The issue has been fixed in version [1.3.1](https://github.com/razorpay/razorpay-android-sample-app/releases/tag/v1.3.1) of Checkout SDK.
