### ISSUE TITLE
QRcode scanner missing

### ISSUE THREAD

**Issue by deepakpradeep1188** [razorpay/razorpay-android-sample-app#211]
I changed to RazorPay version 1.6.6, but now QRcode scanner is missing in RazorPay view. Should i integrate anything extra in latest version to enable QR code scanner?

**Comment by clint22** [comment]
Same issue. Here. Pay using the QR code option ( Scan the QR code option using your UPI app ) is not showing anymore in the latest update. Instead, another option like, pay using apps ( You will be redirected to your UPI apps ) option is showing. If this is a major update, should have notified the clients. Our apps are running Razorpay in production and QR code scanning was an integral feature for us. Any updates?

**Comment by vivekshindhe** [comment]
@deepakpradeep1188 @clint22 The "Scan QR code using UPI" option has never been enabled for mobile applications. It was only available on the web. We apologize if there was any sort of miscommunication from our end regarding this. Closing this issue.

**Comment by clint22** [comment]
Hi @vivekshindhe 
We were using the version 'com.razorpay:checkout:1.4.9' at the time when our apps went to production. I'll attach the screenshot of the Android app with the "Scan QR Code using UPI" option. Our apps are Kiosks used by the general public. So it is an important feature for us. Request you to reopen the issue. 
![old_razorpay_view](https://user-images.githubusercontent.com/9026966/111738604-a8edba00-88a7-11eb-8abe-eb6cde12dbf8.png)

**Comment by sumedht** [comment]
@clint22 Can u share ur MID on sumedh.tambat@razorpay.com, vivek.shindhe@razorpay.com

**Comment by clint22** [comment]
@sumedht Please check your mail. Thank you.

**Comment by clint22** [comment]
Hi,
I have shared the mail ID. Please check.

**Comment by NandaKishorJeripothula** [comment]
@clint22 could you please the device dimensions of screen & screenshot to verify on our end.

**Comment by clint22** [comment]
Hi @NandaKishorJeripothula 
This is the model. 
[https://www.flipkart.com/lenovo-tab-4-10-2-gb-ram-16-rom-10-1-inch-wi-fi-4g-tablet-slate-black/p/itmffm425jnehvuu](url)

**Comment by NandaKishorJeripothula** [comment]
@clint22 resolved.// @sumedht @vivekshindhe
