### ISSUE TITLE
Reference to Sample Java class

### ISSUE THREAD

**Issue by SUMIT0733** [razorpay/razorpay-android-sample-app#212]
When we refer PaymentActivity.java, they don't have included Order_id in JsonObject andsetKeyID in java class as shown in Documentation, I am confused what to refer, this java class or documentation.

I'm getting error like : "Println needs a message" in startPayment method exception.

**Comment by vivekshindhe** [comment]
@SUMIT0733 the PaymentActivity.class is a reference to how the code should be. As such, it does not contain all the pre-requisites that need to be done by you in them. The process for integration should be followed as per the document. If you could send us a code sample of what you've implemented we should be able to help more in this case.

**Comment by SUMIT0733** [comment]
Thanks!, now problem got resolved, I don't know what happened, but I started integration from scratch and it worked. Thanks again!!.
