### ISSUE TITLE
Option to set language 

### ISSUE THREAD

**Issue by tejasCodenicely** [razorpay/razorpay-android-sample-app#213]

**Comment by sumedht** [comment]
@tejasCodenicely Can u plz describe ur issue so it will be easy for us to understand & work upon it

**Comment by tejasCodenicely** [comment]
@sumedht  I am need an option to set default language of the sdk

**Comment by sumedht** [comment]
@razorpay/techpgintegrations

**Comment by sumedht** [comment]
@tejasCodenicely can u share details where u will be reachable to have a more detail discussion?

**Comment by tejasCodenicely** [comment]
@sumedht  as you know sdk has option of eng and hindi now, when i open the sdk it currently by default it has eng selected, suppose my app has in app language change option and i want to change the language of the sdk according to the language my app currently has i cannot do that right.

**Comment by sumedht** [comment]
@tejasCodenicely 
We get the feedback. We currently have the option of setting a default other than English from the dashboard. This will change the render language for all your users. We will consider your  feedback of having a param to change the language on Checkout as an input for prioritisation in the upcoming quarters
