### ISSUE TITLE
Razorpay giving HTML code of rupee instead of symbol

### ISSUE THREAD

**Issue by sudeshim3** [razorpay/razorpay-android-sample-app#215]
![image](https://user-images.githubusercontent.com/34063388/111963085-22401380-8b19-11eb-97d5-3e78c7fc4c3e.png)

## Description
Razorpay is not showing the symbol of rupee(₹). instead, it is showing the Unicode decimal i.e., &#8377; 

`  
    JSONObject().apply {

    put("currency", "INR")
    put("amount", payableAmount.toInt())
    put("email", email)
    put("order_id", orderId)
    put("method", "netbanking")
    put("bank", bankCode)
}`

## Razorpay SDK Version :
I am currently using `razorpay-android-3.8.7`

### What you did:
In Razorpay documentation, it is mentioned that currency param is optional and the default is taken as rupee. However, on not passing currency, the SDK throws an error. I tried this to find if the default currency ₹  shows up. But that's not the case.

This issue is appearing for the last two weeks(approx..)

**Comment by sudeshim3** [comment]
@sumedht can you or someone in your team help with this. Thanks

**Comment by vivekshindhe** [comment]
@sudeshim3 Thanks for bringing this to our notice. We are working on this from our end. Will have an update for you soon.

**Comment by sumedht** [comment]
@sudeshim3 It's fixed now
