### ISSUE TITLE
Hide Google pay and PhonePe from Razor pay UI

### ISSUE THREAD

**Issue by deepakpradeep1188** [razorpay/razorpay-android-sample-app#217]
Currently in razor pay UI , GooglePay and PhonePE application is shown. Is there a way to hide that? since we are implementing razor pay in kiosk ,so we are not making use of those applications. just entering UPI id and doing payment meets our requirement

**Comment by sumedht** [comment]
@razorpay/techpgintegrations

**Comment by sumedht** [comment]
@deepakpradeep1188 Using SDK integration or webview integration?

**Comment by deepakpradeep1188** [comment]
Android SDK integration

**Comment by Anoop-98** [comment]
By my understanding for your use case, only having the "collect" flow (entering UPI id and making the payment) is required and not intent flow(opening up the PSP apps). For such a use case, use the following snippet and add it to your options object before initiating the checkout. Should meet your requirement.
             JSONObject method = new JSONObject();
             JSONObject upi= new JSONObject();
            upi.put("collect",true);
            upi.put("intent",false);
            method.put("upi",upi);
            options.put("method",method);

**Comment by deepakpradeep1188** [comment]
@AnoopRz  I integrated the above code but still Google pay is showing as a "preferred payment method" in Razor pay UI

**Comment by AnoopRz** [comment]
@deepakpradeep1188  Preferred methods visible is due to your previous tries(which will not be same for different devices), clearing the cache should fix it.

**Comment by deepakpradeep1188** [comment]
@AnoopRz  THANKS ANOOP..... its fixed...thanks
