### ISSUE TITLE
Android RunTime Exception in webview of checkout file

### ISSUE THREAD

**Issue by prudhvir3ddy** [razorpay/razorpay-android-sample-app#218]
## Description
everything was working normal till yesterday but today we got a crashlytics spike alert in android 10 and android 11 devices. 

looks like issue is in webview that razorpay uses. 

```
Caused by java.lang.UnsatisfiedLinkError
dlopen failed: "/data/app/com.google.android.webview-DXm47ujjU5OAAtXwqWpFMg==/lib/arm/libwebviewchromium.so" is 32-bit instead of 64-bit
```

```

wH.j (wH.java:17)
wH.l (wH.java:5)
org.chromium.android_webview.AwBrowserProcess.h (AwBrowserProcess.java:9)
com.android.webview.chromium.WebViewChromiumFactoryProvider.f (WebViewChromiumFactoryProvider.java:87)
android.webkit.WebView.<init> (WebView.java:328)
com.razorpay.Checkout.preload (Checkout.java:187)

```

## Razorpay SDK Version :
1.6.6

## Android OS Version :
android 10, 11 

## Steps To Reproduce
not reproduced yet

for now i have very less info, i'll be working on giving more information and update this issue, meanwhile if anyone already has context of this bug then they can look into this.

**Comment by sumedht** [comment]
@prudhvir3ddy On any specific device?
looks like there is an issue with Webview & Chrome on 23rd March & it's been fixed with update from Google.
https://www.theverge.com/2021/3/22/22345696/google-android-apps-crashing-fix-system-webview
https://www.google.com/appsstatus#hl=en&v=issue&sid=1&iid=aa75515d184a2423be444d676b7ebf45

**Comment by prudhvir3ddy** [comment]
@sumedht thanks for the update. 

realme and oppo devices.

issue started on 24th march for me. 

may be some users haven't yet updated from the playstore.  closing this issue for now.
