### ISSUE TITLE
Bug in Razorpay 1.2.1 (class name (com/razorpay/ʼ$iF) does not match path (com/razorpay/��$iF.class))

### ISSUE THREAD

**Issue by vivekkiran** [razorpay/razorpay-android-sample-app#22]
<img width="803" alt="screen shot 2017-03-21 at 8 58 26 pm" src="https://cloud.githubusercontent.com/assets/5557539/24155527/1e1cef64-0e7a-11e7-8bb3-a3637bd214d7.png">
<img width="799" alt="screen shot 2017-03-21 at 8 58 06 pm" src="https://cloud.githubusercontent.com/assets/5557539/24155529/1e918644-0e7a-11e7-86d3-3fed3309669d.png">

**Comment by hariramsvnit** [comment]
Are you using progaurd or dexgaurd? if yes then please add these rules https://docs.razorpay.com/v1/page/android-sdk-v10x#section-proguard-rules
