### ISSUE TITLE
success Url

### ISSUE THREAD

**Issue by MaheshCapcee** [razorpay/razorpay-android-sample-app#23]
how to store payment success and failure details in my server

**Comment by hariramsvnit** [comment]
You need to implement [PaymentResultListner](https://github.com/razorpay/razorpay-android-sample-app/blob/master/app/src/main/java/com/razorpay/sampleapp/PaymentActivity.java#L15) in your activity, when payment is success you will get callback in [onPaymentSucess](https://github.com/razorpay/razorpay-android-sample-app/blob/master/app/src/main/java/com/razorpay/sampleapp/PaymentActivity.java#L73) method. You will also get payment id in onPaymentSucess method, you need to handle it after that.
