### ISSUE TITLE
Dependency failing

### ISSUE THREAD

**Issue by dishantshah99** [razorpay/razorpay-android-sample-app#231]
In project 'app' a resolved Google Play services library dependency depends on another at an exact version (e.g. "[15.0.
1]", but isn't being resolved to that version. Behavior exhibited by the library will be unknown.

Dependency failing: com.google.android.gms:play-services-stats:15.0.1 -> com.google.android.gms:play-services-basement@[
15.0.1], but play-services-basement version was 17.0.0.

**Comment by vivekshindhe** [comment]
@dishantshah99 Closing ticket due to inactivity. Hoping the issue was resolved. In case it wasn't please add a comment here or create another ticket for the same. Thank you.
