### ISSUE TITLE
Razorypay Checkout Fragment Already Added 

### ISSUE THREAD

**Issue by sachin-designs** [razorpay/razorpay-android-sample-app#234]
## Description :

During every 1st time razorpay checkout it throws a illegal state exception which could crash the application. However after the first razorpay checkout. it works smoothly. 

Please find the exception below

**Exception: java.lang.IllegalStateException: Fragment already added: Checkout{77a5497 #1}**

Which says Fragment already added.
However code does the Checkoud.preload(context) for only once in my MainActivity

## Razorpay SDK Version :
 'com.razorpay:checkout:1.6.6'

## Android OS Version :
All the Android os above sdk version 24

### What you did:
After launching the app tried to do razorpay checkout for every 1st checkout it gives fragment already added exception and from second time it works smoothly

## What happened:
Checkout Throwed a exception  **Exception: java.lang.IllegalStateException: Fragment already added: Checkout{77a5497 #1}**

Caused by java.lang.IllegalStateException
Fragment already added: Checkout{77a5497 #1}
android.app.FragmentManagerImpl.addFragment (FragmentManager.java:1719)
android.app.BackStackRecord.executeOps (BackStackRecord.java:770)
android.app.FragmentManagerImpl.executeOps (FragmentManager.java:2415)
android.app.FragmentManagerImpl.executeOpsTogether (FragmentManager.java:2210)
android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute (FragmentManager.java:2171)
android.app.FragmentManagerImpl.execPendingActions (FragmentManager.java:2072)
android.app.FragmentManagerImpl.dispatchMoveToState (FragmentManager.java:3062)
android.app.FragmentManagerImpl.dispatchStop (FragmentManager.java:3027)
android.app.FragmentController.dispatchStop (FragmentController.java:228)
android.app.Activity.performStop (Activity.java:8138)
android.app.ActivityThread.callActivityOnStop (ActivityThread.java:4703)
android.app.ActivityThread.performStopActivityInner (ActivityThread.java:4681)
android.app.ActivityThread.handleStopActivity (ActivityThread.java:4756)
android.app.servertransaction.StopActivityItem.execute (StopActivityItem.java:41)
android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2044)
android.os.Handler.dispatchMessage (Handler.java:107)
android.os.Looper.loop (Looper.java:224)
android.app.ActivityThread.main (ActivityThread.java:7562)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:539)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:950)

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.Close the app and launch from first
2.Try using razorpay checkout it will give exception for first time

## Code example:
      public class HomeActivity extends AppCompatActivity implements PaymentResultWithDataListener {
           ..
           ..
           private final Checkout checkout=new Checkout();
           ..
           ..
             @Override
	        protected void onCreate(Bundle savedInstanceState) {
                       ..
                       ..
                       ..
                       Checkout.preload(getApplicationContext());
                       ..
                       ..          
                      button.setOnClickListener(new View.OnClickListener() {
                                ..
                                startPayment(payment_Details,50,api_key);    //api_key got from server and stored
                                ..
                                });
            }

            public  void startPayment(Payment_Details coin_details1, int i, String api_key) {
		      checkout.setKeyID(api_key);

		      checkout.setImage(R.drawable.contazy_main_logo);
		
		      try {
			JSONObject options = new JSONObject();
			JSONObject modal = new JSONObject();
			JSONObject prefill = new JSONObject();
			JSONObject theme = new JSONObject();

			theme.put("color","#38B5FF");

			prefill.put("email",sessionManagement.getProfileEmail());

			modal.put("handleback",false);

			options.put("name", sessionManagement.getProfileName());
			options.put("description", "Credits of "+i+" Coins to wallet");
			options.put("image", "https://firebasestorage.googleapis.com/v0/b/connectdev-794eb.appspot.com/o/ContazyLogo%2Fcontazylogo.jpeg?alt=media&token=292b90d8-46c0-465a-91a6-4df6190c72e2");
			options.put("order_id", coin_details1.getId());//from response of step 3.
			options.put("currency", "INR");
			options.put("amount", coin_details1.getAmount());//pass amount in currency subunits
			options.put("prefill",prefill);
			options.put("theme", theme);
			options.put("modal",modal);

			checkout.open(this, options);

		} catch(Exception e) {
			Log.e("PAYMENT", "Error in starting Razorpay Checkout", e);
		}
	   }
     
           @Override
	   public void onPaymentSuccess(String s, PaymentData paymentData) {
                            postData(paydet, s, paymentData);
	       }
	   @Override
	  public void onPaymentError(int i, String s, PaymentData paymentData) {
		postError();
	       }
      ..
      ..
    }

**Comment by sachin-designs** [comment]
@vivekshindhe It normally occurs on all device and issue occurs only for the first checkout and works fine after that.

**Comment by vivekshindhe** [comment]
@sachin-designs we haven't encountered this issue. Could you please take some time and send a sample project where you are able to see this? It would be really helpful in resolving this issue quicker.

**Comment by sachin-designs** [comment]
@vivekshindhe  thanks I will try to come up with  sample project with issue replicated.

**Comment by Balakubera** [comment]
Same happens in production.. Please fix it.

**Comment by vivekshindhe** [comment]
@sachin-designs before that, I was just watching your payload. Can you try once removing the modal object?

**Comment by sachin-designs** [comment]
@vivekshindhe Yes I have tried removing the modal object and i still see the same issue. 

## Different Issue
And there is one more enhancement ( or Bug ) Which needs to be addressed in razorpay checkout i.e when user performs payment and during payment verification if user tries do press back button it will close the checkout which results in payment cancel even though amount was deducted.

## Solution could be : 
Overriding the onbackpressed of razorypay checkout will give us option of not letting users to go back from checkout so the payment verification gets completed.

**Comment by vivekshindhe** [comment]
If the payment gets canceled refund is also initiated.

**Comment by sachin-designs** [comment]
@vivekshindhe  No in such case Refund is not initiated. Simply event come's into  OnpaymentError method

**Comment by abhirzp** [comment]
In that case, the money debited will be auto refunded to the end user even after the payment going into failed status.

**Comment by vivekshindhe** [comment]
Closing ticket due to inactivity. Please feel free to ask for reopening the ticket or create a new one. Thank you.

**Comment by omkar-tenkale** [comment]
@vivekshindhe 
I'm getting same error, most of the time app crashes, sometimes it works

```
java.lang.IllegalStateException: Fragment already added: Checkout{6e175a3 #1}
                                                                                                    	at android.app.FragmentManagerImpl.addFragment(FragmentManager.java:1714)
                                                                                                    	at android.app.BackStackRecord.executeOps(BackStackRecord.java:770)
                                                                                                    	at android.app.FragmentManagerImpl.executeOps(FragmentManager.java:2410)
                                                                                                    	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2205)
                                                                                                    	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
                                                                                                    	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
                                                                                                    	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:742)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:205)
                                                                                                    	at android.os.Looper.loop(Looper.java:294)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8176)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**Comment by omkar-tenkale** [comment]
It happens when `checkout.open(activity,options)` is called multiple times
The checkout activity is most probably singleInstance so it tries to add checkout fragment again and crashes

I fixed it my making sure I dont call  checkout.open(..) when a checkout is already in progress
