### ISSUE TITLE
Unable to user fragmentManager inside onPaymentSuccess and onPaymentError

### ISSUE THREAD

**Issue by pratikvar** [razorpay/razorpay-android-sample-app#238]
## Description

Can not use `supportFragmentManager` for any of fragment or dialog fragment transaction as `supportFragmentManager.isStateSaved` return `true` inside `onPaymentSuccess` and `onPaymentError`

## Razorpay SDK Version :
com.razorpay:checkout:1.6.6

## Android OS Version :
currently using Android Pie and Oreo

### What you did:
Trying to show `DialogFragment` to notify a user about success and failure 

### What happened:
`onPaymentSuccess` and `onPaymentError` always throwing error as `Your onPaymentSuccess method is throwing an error. Wrap the entire code of the method inside a try catch.`

## Steps To Reproduce
Try to show `DialogFragment` from `onPaymentSuccess` or `onPaymentError` method

### Suggested solution:
When I have digged into show method of fragment transaction, I noticed commit method is throwing error. investigating more, I found that supportFragmentManager.isStateSaved returns true which means [HERE](https://developer.android.com/reference/androidx/fragment/app/FragmentManager?hl=en#isStateSaved())

**Comment by vivekshindhe** [comment]
@pratikvar Apart from what's there in the android documentation, 

https://developer.android.com/reference/androidx/fragment/app/FragmentTransaction#commitAllowingStateLoss()

we won't be able to help you much here because this would be an android related issue.

**Comment by vivekshindhe** [comment]
Closing the ticket due to inactivity. Please feel free to open another ticket.
