### ISSUE TITLE
Android 12 Support: Set android:exported in AndroidManifest.xml

### ISSUE THREAD

**Issue by rnkdsh** [razorpay/razorpay-android-sample-app#248]
## Description

I recently update my `compileSdkVersion` and `targetSdkVersion` to 31. Now I get this error when I try to build the app.

> Manifest merger failed : android:exported needs to be explicitly specified for <activity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

## Razorpay SDK Version :
1.6.10

## Android OS Version :
Android 12(31)

### What you did:

Trying to build or run the app.

### What happened:

Build Failed:

> Manifest merger failed : android:exported needs to be explicitly specified for <activity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1. Update `compileSdkVersion` and `targetSdkVersion` to 31.
2. Run the app.

### Suggested solution:

Add `android:exported="false"` or `android:exported="true"` in the manifest in each supported components in the Razorpay Android SDK.

## Code example, screenshot, or link to a repository:

There is no example needed. It is happening every time when `compileSdkVersion` and `targetSdkVersion` set to 31. If I change back to 30 it works.

## Temporary workaround:

Adding this code in the  `AndroidManifest.xml` will override the values of the Razorpay Android SDK and it will work.

```
<receiver
    android:name="com.razorpay.RzpTokenReceiver"
    android:exported="false">
    <intent-filter>
        <action android:name="rzp.device_token.share" />
    </intent-filter>
</receiver>

<activity
    android:name="com.razorpay.CheckoutActivity"
    android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
    android:exported="true"
    android:theme="@style/CheckoutTheme">
    <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <data
            android:host="rzp.io"
            android:scheme="io.rzp" />
    </intent-filter>
</activity>
```

**Comment by sumedht** [comment]
@rnkdsh Will fix this in our next release

**Comment by prudhvir3ddy** [comment]
@sumedht any update ?

**Comment by MrRezwan88** [comment]
@sumedht Please fix it ASAP

**Comment by rrsaikat** [comment]
@sumedht Eagerly waiting for to be fixed, please do it ASAP

**Comment by rrsaikat** [comment]
@sumedht please fix it ASAP :/

**Comment by rnkdsh** [comment]
> @sumedht please fix it ASAP :/

you can use temporary workaround until fixed :)

**Comment by aexyn-contact** [comment]
When can we expect this to be fixed? or please advise temporary workaround ?

**Comment by rnkdsh** [comment]
> When can we expect this to be fixed? or please advise temporary workaround ?

Just add this is your manifest:

```
<receiver
    android:name="com.razorpay.RzpTokenReceiver"
    android:exported="false">
    <intent-filter>
        <action android:name="rzp.device_token.share" />
    </intent-filter>
</receiver>

<activity
    android:name="com.razorpay.CheckoutActivity"
    android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
    android:exported="true"
    android:theme="@style/CheckoutTheme">
    <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <data
            android:host="rzp.io"
            android:scheme="io.rzp" />
    </intent-filter>
</activity>
```

**Comment by SumeetMoray** [comment]
Yes i am facing the same issue ... please fix soon !

**Comment by SumeetMoray** [comment]
> When can we expect this to be fixed? or please advise temporary workaround ?

Yes there is a temporary work around ... Goto Manifest then click Merged Manifest ... find RazorPay library - this will open razorpay manifest and manually add exported tag in the razorpay manifest. 

But you need to do it everytime you restart your android studio. This is not a permanent solution !

**Comment by SumeetMoray** [comment]
This is such a simple issue ... but you guys havent fixed it even after 4 months ... Very Lazy !

**Comment by SumeetMoray** [comment]
> @rnkdsh Will fix this in our next release

Hello ... This is such a simple issue ... which will not take more than 10 minutes to fix ... why it is taking so many months to fix it !
We are really wasting lot of extra time because of this small issue ... Please fix it !

**Comment by SaurabhPurohit20** [comment]
Fix this issue as soon as possible...

**Comment by GauravCalidig** [comment]
+1

**Comment by Innocent-Akim** [comment]
<receiver
    android:name="com.razorpay.RzpTokenReceiver"
    android:exported="false">
    <intent-filter>
        <action android:name="rzp.device_token.share" />
    </intent-filter>
</receiver>

<activity
    android:name="com.razorpay.CheckoutActivity"
    android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
    android:exported="true"
    android:theme="@style/CheckoutTheme">
    <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <data
            android:host="rzp.io"
            android:scheme="io.rzp" />
    </intent-filter>
</activity>

**Comment by vivekshindhe** [comment]
Hello all, it's been fixed and released with version 1.6.16. Please update to that. Thank you. Closing the ticket.

**Comment by SumeetMoray** [comment]
@vivekshindhe This isnt fixed  ...  please put exported tag in receiver also ... then it will be fixed ... 

![Screenshot from 2022-01-18 14-41-07](https://user-images.githubusercontent.com/10581266/149906612-df069b6c-9f0c-4848-a990-766e7351b305.png)

**Comment by rnkdsh** [comment]
> @vivekshindhe This isnt fixed ... please put exported tag in receiver also ... then it will be fixed ...
> 
> ![Screenshot from 2022-01-18 14-41-07](https://user-images.githubusercontent.com/10581266/149906612-df069b6c-9f0c-4848-a990-766e7351b305.png)

Right. It is not fixed yet. 

Looks like SDK updated without testing 😄

**Comment by vivekshindhe** [comment]
Apologies folks, looks like we missed that. Will try to update asap. Thank you for pointing it out.

**Comment by dipakbari4** [comment]
Already mentioned on [Official Site](https://razorpay.com/docs/payment-gateway/android-integration/standard/faqs/) to override the above snippets in AndroidManifest.xml

```xml
<application>
        <receiver android:name="com.razorpay.RzpTokenReceiver"
            android:exported="false">
            <intent-filter>
                <action android:name="rzp.device_token.share" />
            </intent-filter>
        </receiver>

        <activity
            android:name="com.razorpay.CheckoutActivity"
            android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
            android:exported="true"
            android:theme="@style/CheckoutTheme" >
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <data
                    android:host="rzp.io"
                    android:scheme="io.rzp" />
            </intent-filter>
        </activity>
</application>
```

**Comment by vivekshindhe** [comment]
This has been updated in v1.6.17. Please update to that. Closing the ticket for now. Thank you for your patience

**Comment by RRCDATA** [comment]
Maui  core 7 user add  

<application android:allowBackup="true" android:icon="@mipmap/appicon" android:supportsRtl="true" android:label="xxxx">

  <receiver
   android:name="com.razorpay.RzpTokenReceiver"
   android:exported="false">
    <intent-filter>
      <action android:name="rzp.device_token.share" />
    </intent-filter>
  </receiver>

  <activity
      android:name="com.razorpay.CheckoutActivity"
      android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
      android:exported="true"
      android:theme="@style/CheckoutTheme">
    <intent-filter>
      <action android:name="android.intent.action.MAIN" />
      <data
          android:host="rzp.io"
          android:scheme="io.rzp" />
    </intent-filter>
  </activity>
</application>

**Comment by RRCDATA** [comment]
`<application android:allowBackup="true" android:icon="@mipmap/appicon" android:supportsRtl="true" android:label="xxxxx">

  <receiver
   android:name="com.razorpay.RzpTokenReceiver"
   android:exported="false">
    <intent-filter>
      <action android:name="rzp.device_token.share" />
    </intent-filter>
  </receiver>

  <activity
      android:name="com.razorpay.CheckoutActivity"
      android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
      android:exported="true"
      android:theme="@style/CheckoutTheme">
    <intent-filter>
      <action android:name="android.intent.action.MAIN" />
      <data
          android:host="rzp.io"
          android:scheme="io.rzp" />
    </intent-filter>
  </activity>
</application>`
