### ISSUE TITLE
Disable paylater option in Razorpay UI

### ISSUE THREAD

**Issue by namangt68** [razorpay/razorpay-android-sample-app#249]
## Description

How to disable Pay Later option in Android UI.
## Razorpay SDK Version : 
1.6.6

### What you did:
Tried to disable paylater option like this as mentioned [here](https://razorpay.com/docs/payments/payments/payment-methods/)

```
// Customized payment options
            JSONObject paymentOption = new JSONObject();
            paymentOption.put("paylater","false");
            paymentOption.put("netbanking","false");
            paymentOption.put("card","true");
            paymentOption.put("wallet","true");
            paymentOption.put("upi","false");
            paymentOption.put("emi","false");

            options.put("method",paymentOption);
```
### What happened:
Paylater is still showing in options.

![WhatsApp Image 2021-08-04 at 17 49 39 (2)](https://user-images.githubusercontent.com/6892483/128179989-95da7363-6771-4c7a-8258-ce09c5c1ad54.jpeg)

**Comment by Rajkumarrmani** [comment]
I'm facing same thing. How to disable paylater.

**Comment by vivekshindhe** [comment]
@namangt68 @Rajkumarrmani Thanks for reaching out. Please use the below link to disable certain payment methods https://razorpay.com/docs/payment-links/api/new/advanced-options/customize/payment-methods/

**Comment by namangt68** [comment]
@vivekshindhe paylater option not mentioned in the documentation link you shared. I raised a razorpay ticket to disable pay later option that solved the issue

**Comment by AkshayAshokCode** [comment]
@namangt68 @vivekshindhe  So the PayLater method can only be disabled by raising a Razorpay ticket? Is no programmatical or dashboard solution available?

**Comment by AkshayAshokCode** [comment]
@namangt68 I also raised a Razorpay ticket but the team said it's not possible to Disable the 'Pay Later' method.
