### ISSUE TITLE
Error : onPaymentError probably not implemented in your activity

### ISSUE THREAD

**Issue by ansh2166** [razorpay/razorpay-android-sample-app#258]
Kindly help me, I face this error, my code is : 

```
public void StartPayment(String key) {
        co.setKeyID(key);
        try {
            JSONObject options = new JSONObject();
            options.put("name", "test");
            options.put("description", "test payment to test sdk");
            options.put("send_sms_hash", true);
            options.put("allow_rotation", true);
            options.put("image", "https://s3.amazonaws.com/rzp-mobile/images/rzp.png");
            options.put("currency", "INR");
            options.put("amount", 100);
            options.put("theme.color", "#ff914d");
            options.put("subscription_id", "test1234");
            options.put("callback_url", "razorpay.com");
            options.put("redirect", true);
            options.put("recurring", false);
            options.put("timeout", 1000);
            options.put("remember_customer", true);
            options.put("customer_id", "j1uyt2"); // random
            JSONObject retryObj = new JSONObject();
            retryObj.put("enabled", true);
            retryObj.put("max_count", 5);
            options.put("retry", retryObj);
            co.open(activity, options);
        } catch (Exception e) {
             e.printStackTrace();
        }
    }

  public void ClearUserData(){
      co.clearUserData(context);
  }
     @SuppressWarnings("unused")
     @Override
    public void onPaymentSuccess(String razorpayPaymentID, PaymentData paymentData) {
        PaymentSuccess(razorpayPaymentID);

    }
    @SuppressWarnings("unused")
    @Override
    public void onPaymentError(int code, String response, PaymentData paymentData) {
           PaymentError(code, response);
    }



```

 class implements PaymentResultWitDataListener, I really need help

**Comment by vivekshindhe** [comment]
@ansh2166 it looks like you haven't implemented the PaymentResultListener in the activity. Please refer to the activity class in the repo.


Focus on the line

public class MainActivity extends Activity implements PaymentResultListener

Adding the implements PaymentResultListener to the activity should resolve this error for you.

**Comment by vivekshindhe** [comment]
@ansh2166 app/src/main/java/com/razorpay/sampleapp/java/PaymentActivity.java

Line 70

**Comment by vivekshindhe** [comment]
@ansh2166 Let me know if this resolved the issue for you

**Comment by ansh2166** [comment]
@vivekagarwal1984 I added PaymentResultListener but still error comes

**Comment by vivekshindhe** [comment]
Can you share the whole file where you are doing this? If privacy is a concern you can mail it to vivek.shindhe@razorpay.com.

**Comment by ansh2166** [comment]
Actually, its not privacy concern, but maybe u wont understand it, as I am working on a task to make Razorpay Be Usable and implementable with MIT Appinventor (Ai2.appinventor.mit.edu) , so anyone can implement razorpay in apps without any knowledge to code, well, Overall its Java code only but, its bit different from one we used generally,

**Comment by ansh2166** [comment]
It will be useful for non-coders to implement razorpay in apps if I succeed in this as they will be able to just implement razorpay using a visual programming interface

**Comment by vivekshindhe** [comment]
I've worked with app inventor. Please send

**Comment by ansh2166** [comment]
> I've worked with app inventor. Please send

Nice to know, so ya, my code is as follows

```
package com.kabby.RazorpayPayments;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.util.Log;
import com.google.appinventor.components.annotations.*;
import com.google.appinventor.components.common.ComponentCategory;
import org.json.JSONObject;
import com.razorpay.*;
import com.google.appinventor.components.runtime.AndroidNonvisibleComponent; 
import com.google.appinventor.components.runtime.ComponentContainer; 
import com.google.appinventor.components.annotations.*; 
import com.google.appinventor.components.annotations.androidmanifest.*; 
import com.razorpay.Checkout;
import com.razorpay.PaymentResultListener;
import com.google.appinventor.components.runtime.EventDispatcher; 
import com.google.appinventor.components.common.*;
@DesignerComponent(
    version = 1,
    description = "Razorpay",
    category = ComponentCategory.EXTENSION,
    nonVisible = true,
    iconName = "")
@UsesLibraries(libraries = "razorpay.jar, api.jar, base.jar, basement.jar, tasx.jar")
@SimpleObject(external = true)
@UsesActivities(activities = {@ActivityElement(name = "com.razorpay.CheckoutActivity", configChanges="keyboard|keyboardHidden|orientation|screenSize" )})
@UsesPermissions(permissionNames = "android.permission.INTERNET")
@UsesApplicationMetadata(metaDataElements = { 
@MetaDataElement(name = "com.google.android.gms.wallet.api.enabled", value = "true")})

public class RazorpayPayments extends AndroidNonvisibleComponent implements PaymentResultWithDataListener {

    private Context context;
    private Activity activity;
    private String imgUrl;
    private String name;
    private String description;
    private String currency;
    private int amount;
    private String key;
    private String paymentHex;
    private String subscriptionId;
    private String cbackUrl;
    private Checkout co;
    private int timeout;

    public RazorpayPayments(ComponentContainer container){
        super(container.$form());
        this.activity = container.$context();
        this.context = container.$context();
        Checkout.preload(activity.getApplicationContext());
        co = new Checkout();
    }
@SimpleFunction() 
public void StartPayment(String customerId) {
        co.setKeyID(key);
        try {
            JSONObject options = new JSONObject();
            options.put("name", name);
            options.put("description", description);
            options.put("send_sms_hash", sendSmsHash);
            options.put("allow_rotation", alrep);
            options.put("image", imgUrl);
            options.put("currency", currency);
            options.put("amount", amount);
            co.open(activity, options);
        } catch (Exception e) {
             String errorMessage = e.getMessage();
             ErrorOccured(errorMessage);
             e.printStackTrace();
        }
    }
    @SimpleEvent
  public void ErrorOccured(String errorMessage) {
    EventDispatcher.dispatchEvent(this, "ErrorOccured", errorMessage);
  }
  @SimpleEvent
  public void PaymentError(int code, String response) {
    EventDispatcher.dispatchEvent(this, "PaymentError", code, response);
  }
  @SimpleEvent
  public void PaymentSuccess(String razorpayPaymentID) {
    EventDispatcher.dispatchEvent(this, "PaymentSuccess", razorpayPaymentID);
  }
    @Override
    public void onPaymentSuccess(String razorpayPaymentID, PaymentData paymentData) {
        PaymentSuccess(razorpayPaymentID);

    }
    @SuppressWarnings("unused")
    @Override
    public void onPaymentError(int code, String response, PaymentData paymentData) {
           PaymentError(code, response);
    }
  @DesignerProperty(
      defaultValue = "Your Api Key",
      editorType = PropertyTypeConstants.PROPERTY_TYPE_STRING)
  @SimpleProperty
  public void ApiKey(String bru) {
    key = bru;
  }
  @DesignerProperty(
      defaultValue = "Company Name",
      editorType = PropertyTypeConstants.PROPERTY_TYPE_STRING)
  @SimpleProperty
  public void CompanyName(String bru) {
    name = bru;
  }
  @DesignerProperty(
      defaultValue = "Payment Description",
      editorType = PropertyTypeConstants.PROPERTY_TYPE_STRING)
  @SimpleProperty
  public void Description(String bru) {
    description = bru;
  }
  @DesignerProperty(
      defaultValue = "Payment Currency",
      editorType = PropertyTypeConstants.PROPERTY_TYPE_STRING)
  @SimpleProperty
  public void Currency(String bru) {
    currency = bru;
  }
  @DesignerProperty(
      defaultValue = "100",
      editorType = PropertyTypeConstants.PROPERTY_TYPE_INTEGER)
  @SimpleProperty
  public void Amount(int bru) {
    amount = bru;
  }

  @SimpleFunction
  public void ClearUserData(){
      co.clearUserData(context);
  }

}

```

**Comment by vivekshindhe** [comment]
@ansh2166 Can you try once with PaymentResultListener? The code seems correct so I don't know what is exactly throwing the error. Also could you please send the compiler error logs that you get when you try to run this?

**Comment by ansh2166** [comment]
> @ansh2166 Can you try once with PaymentResultListener? The code seems correct so I don't know what is exactly throwing the error. Also could you please send the compiler error logs that you get when you try to run this?

I tried with PaymentResultListener firstly but, it didnt work too

**Comment by vivekshindhe** [comment]
Can you send the error message you get? The whole thing?

**Comment by vivekshindhe** [comment]
Hey @ansh2166 Since this is a hacky way of implementing this, these are unknown waters for us as well.
The PR to use .aar files in the component is ready, you can reference that here, 
https://github.com/mit-cml/appinventor-sources/pull/2230
Also, looks like you also have to reference both the classes.jar and the aar file in the UsesLibrary section.   
You can have a look at these, threads
https://community.appinventor.mit.edu/t/how-do-i-use-aar-in-my-component/294/3
https://github.com/mit-cml/appinventor-sources/blob/master/appinventor/components/build.xml 

Hope these help you out.

**Comment by ansh2166** [comment]
I used it as a component too

**Comment by ansh2166** [comment]
I just wonder wy it only displays  onPaymentError probably not implemented in your activity and not onPaymentSuccess, onPaymentSuccess seems successfully implemented

@vivekshindhe i just want to know, if any setPaymentListener like method is available in Sdk, if so, it will be easily implementable

**Comment by vivekshindhe** [comment]
@ansh2166 I get that sirji. We will add it to the pipeline as well.

**Comment by ansh2166** [comment]
@vivekshindhe any news?

**Comment by vivekshindhe** [comment]
@ansh2166 Not yet. Will keep you updated on the same.

**Comment by AsianKungFu** [comment]
If anyone is still getting the error after implementing PaymentResultListener, you're probably starting the razorpay payment inside a fragment.

The documentation notes that "If you are calling the payment start method from inside a fragment, ensure that the fragment's parent activity implements the PaymentResultListener".

Try implementing PaymentResultListener in the mainactivity that loads your fragments.

**Comment by nirmalswmnthn** [comment]
Hi Razorpay Team,

**Comment by nirmalswmnthn** [comment]
Hi Razorpay, as per docs implementation is 'com.razorpay:checkout:1.6.17' but I'm able to use only 'com.razorpay:checkout:1.6.10'. Android studio also says 1.6.10 is the recent updated version.

![razorpay_version_issue](https://user-images.githubusercontent.com/72009676/156114542-32f2c9e7-7feb-4fa0-8f27-547eeb4a9921.jpeg)

**Comment by nirmalswmnthn** [comment]
Hi Razorpay, the latest version supported in android is 'com.razorpay:checkout:1.6.10' BUT as per docs it says 'com.razorpay:checkout:1.6.17'. I'm unable to implement 'com.razorpay:checkout:1.6.17', Please can you clarify this. 

![razorpay_version_issue](https://user-images.githubusercontent.com/72009676/156114968-1120b063-c683-48b1-b5a4-9356cda33a48.jpeg)

**Comment by vivekshindhe** [comment]
@nirmalswmnthn yeah, so it doesn't work every time for some reason. You can check [https://mvnrepository.com/artifact/com.razorpay/checkout]( Maven) for the latest version

**Comment by nirmalswmnthn** [comment]
I've downloaded .aar library and included it. Now Andorid Studio is recognizing the library BUT on running its throwing 'Could not resolve project error'.

![image](https://user-images.githubusercontent.com/72009676/156123836-32a96f26-f625-4674-847f-1906f0105f5d.png)

**Comment by vivekshindhe** [comment]
@nirmalswmnthn you don't need to do that. Invalidate caches and restart android studio and it the dependency error will be resolved. Using the aar file manually is something we wouldn't recommend. Also there are internal dependencies that the SDK uses that are included in the POM file.

**Comment by nirmalswmnthn** [comment]
> @nirmalswmnthn you don't need to do that. Invalidate caches and restart android studio and it the dependency error will be resolved. Using the aar file manually is something we wouldn't recommend. Also there are internal dependencies that the SDK uses that are included in the POM file.

Yes even I dont want to use aar file, but direct implementation

 implement 'com.razorpay:checkout:1.6.17' ---> is not working

none of the razorpay classes like Checkout can be used. How to implement --> 'com.razorpay:checkout:1.6.17'. Pls help,

**Comment by vivekshindhe** [comment]
@nirmalswmnthn did you invalidate the cache and restart android studio?

**Comment by nirmalswmnthn** [comment]
Yes, now its working. Thanks.

**Comment by nirmalswmnthn** [comment]
Just a suggestion, please update sample app with latest version, so that we can verify it with a working code.

**Comment by sagarrawal9769** [comment]
> @ansh2166 it looks like you haven't implemented the PaymentResultListener in the activity. Please refer to the activity class in the repo.
> 
> Focus on the line
> 
> public class MainActivity extends Activity implements PaymentResultListener
> 
> Adding the implements PaymentResultListener to the activity should resolve this error for you.

hey i have to implement the payment in a fragment what can i do for that , idw to implement payment in activity in any chance

**Comment by brij21141** [comment]
> If anyone is still getting the error after implementing PaymentResultListener, you're probably starting the razorpay payment inside a fragment.
> 
> The documentation notes that "If you are calling the payment start method from inside a fragment, ensure that the fragment's parent activity implements the PaymentResultListener".
> 
> Try implementing PaymentResultListener in the mainactivity that loads your fragments.

Thanks your approach worked 
thanks again

**Comment by VosoUser** [comment]
3----No appropriate payment method found.
why this code and meaning of massage

**Comment by riyazparasara** [comment]
**Error**:
"onPaymentSuccess probably not implemented in your activity."

**Reason**:
This error occurs when you implement Razorpay Checkout in a fragment instead of directly in an activity. The Razorpay SDK expects the onPaymentSuccess and onPaymentError callbacks to be handled by an activity, not a fragment. As a result, if you implement the checkout process within a fragment, these callbacks won’t be triggered correctly, leading to the error.

**Solution**:
To resolve this, you should handle the payment callbacks (onPaymentSuccess, onPaymentError, and onExternalWalletSelected) in the activity that hosts your fragment. Once the activity receives these callbacks, it should pass the data to the appropriate fragment.

**Steps to Implement the Solution:**
Implement the Callbacks in the Hosting Activity:

Ensure your activity (e.g., DashboardActivity) implements PaymentResultWithDataListener and ExternalWalletListener to handle the Razorpay callbacks.
Forward the Callbacks to the Fragment:

In the activity, forward the payment callbacks to the specific fragment (e.g., CheckoutFragment). This can be done by retrieving the current fragment and invoking the corresponding methods.
Retrieve the Fragment Safely:


Example 

`public class DashboardActivity extends AppCompatActivity implements PaymentResultWithDataListener, ExternalWalletListener {
    // ...

    @Override
    public void onPaymentSuccess(String razorpayPaymentID, PaymentData paymentData) {
        // Forward the success callback to the fragment
        CheckoutFragment checkoutFragment = getCheckoutFragment();
        if (checkoutFragment != null) {
            checkoutFragment.onPaymentSuccess(razorpayPaymentID, paymentData);
        }
    }

    @Override
    public void onPaymentError(int code, String response, PaymentData paymentData) {
        // Forward the error callback to the fragment
        CheckoutFragment checkoutFragment = getCheckoutFragment();
        if (checkoutFragment != null) {
            checkoutFragment.onPaymentError(code, response, paymentData);
        }
    }

    @Override
    public void onExternalWalletSelected(String s, PaymentData paymentData) {
        // Forward the wallet selection to the fragment
        CheckoutFragment checkoutFragment = getCheckoutFragment();
        if (checkoutFragment != null) {
            checkoutFragment.onExternalWalletSelected(s, paymentData);
        }
    }

    private CheckoutFragment getCheckoutFragment() {
        // Get the NavHostFragment
        NavHostFragment navHostFragment = (NavHostFragment) getSupportFragmentManager()
                .findFragmentById(R.id.nav_host_fragment_activity_dashboard);

        if (navHostFragment != null) {
            // Get the currently displayed fragment inside the NavHostFragment
            Fragment currentFragment = navHostFragment.getChildFragmentManager().getPrimaryNavigationFragment();

            if (currentFragment instanceof CheckoutFragment) {
                return (CheckoutFragment) currentFragment;
            }
        }
        return null;
    }
}
`
