### ISSUE TITLE
Android 12 as target not buildable due to manifest merge issues

### ISSUE THREAD

**Issue by jacob-abe** [razorpay/razorpay-android-sample-app#269]
"Merging Errors: Error: android:exported needs to be explicitly specified for . Apps targeting Android 12 and higher are required to specify an explicit value for android:exported when the corresponding component has an intent filter defined." 

The razorpay library uses an intent filter in its activities and android:export="false" must be set explicitly in order for gradle to build and apps to be installed on Android 12 devices. 

Observable on Razorpay 1.6.14 as well which is the latest version.

**Comment by vivekshindhe** [comment]
We will be updating the next version with android 12 support. Thank you for your patience. Will comment here once done.

**Comment by mj8894** [comment]
@vivekshindhe: Any updates on this?

**Comment by sumit2607** [comment]
Merging Errors: Error: android:exported needs to be explicitly specified for . Apps targeting Android 12 and higher are required to specify an explicit value for android:exported when the corresponding component has an intent filter defined."

**Comment by SumeetMoray** [comment]
> Merging Errors: Error: android:exported needs to be explicitly specified for . Apps targeting Android 12 and higher are required to specify an explicit value for android:exported when the corresponding component has an intent filter defined."



> @vivekshindhe: Any updates on this?


Guys there is a temporary work around ... Goto Manifest then click Merged Manifest ... find RazorPay library - this will open razorpay manifest and manually add exported tag in the razorpay manifest. 

But you need to do it everytime you restart your android studio. This is not a permanent solution !

**Comment by SumeetMoray** [comment]
> We will be updating the next version with android 12 support. Thank you for your patience. Will comment here once done.

This is such a small issue which can  be fixed easily ... so much developer time is getting wasted due to  this bug ... 
Please fix it Soon !

**Comment by SivakumarPK04867** [comment]
Same Issue from DDIS Technologies. Please resolve it ASAP.
PFA screenshot FYI.

<img width="1792" alt="Screenshot 2022-01-07 at 9 03 04 AM" src="https://user-images.githubusercontent.com/96518219/148487230-07b74449-a962-4e23-9ac6-a400f8f5ea8d.png">

**Comment by mj8894** [comment]
Everyone Please add the below code in your manifest file which should resolve this issue

`<receiver
    android:name="com.razorpay.RzpTokenReceiver"
    android:exported="false">
    <intent-filter>
        <action android:name="rzp.device_token.share" />
    </intent-filter>
</receiver>

<activity
    android:name="com.razorpay.CheckoutActivity"
    android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
    android:exported="true"
    android:theme="@style/CheckoutTheme">
    <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <data
            android:host="rzp.io"
            android:scheme="io.rzp" />
    </intent-filter>
</activity>`

Hope this helps, Its available on the razorpay website as well

**Comment by mj8894** [comment]
Please visit this link for the workaround provided by their team:

https://razorpay.com/docs/payment-gateway/android-integration/standard/faqs/

**Comment by vivekshindhe** [comment]
Hi all, this issue has been resolved in v1.6.17. Please update to the same. Closing the ticket.
