### ISSUE TITLE
Error when building app for Android 12

### ISSUE THREAD

**Issue by SumeetMoray** [razorpay/razorpay-android-sample-app#273]
## Description

I have integrated razorpay checkout library in my android app **implementation 'com.razorpay:checkout:1.6.15'** 

The app fails to build when i upgraded the compile SDK version to 31 which is Android 12 . 
There is an error which occurs at Manifest Merger. 

The error occurs only due to RazorPay dependency and No other dependency. This is verified because error goes away 
when RazorPay Manifest is edited in Android Studio !

## Razorpay SDK Version :
Open `build.gradle`. > Copy `com.razorpay` version here or github URL. 

`implementation 'com.razorpay:checkout:1.6.15'`

## Android OS Version :
Any specific android version if this issue is only occuring on a specific version. 

This issue only occurs when you are building for Android API 31 or Android version 12

### What you did:

I upgraded my compile SDK version and target SDK version to 31 and this error started. This error went away when i modified the 
Manifest file for RazorPay SDK ... but this is only a temporary solution. 

In order to fix this issue permanently you guys need to add `android:exported="false"` in your RazorPay manifest ... 

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.Upgrade Comple SDK version to 31 and Target SDK version to 31 for any android app that includes RazorPay Checkout SDK
2. Read the error message in the logcat or build screen

### Suggested solution:

This error occurs because android 12 (API level 31) requires a mandatory `android:exported="false"` 
tag in the Manifest File for each receiver and activity that has intent-filter tag. 

You simply upgrade your compile SDK and target SDK version to 31 and implement the auto-correct suggestions 
provided by Android Studio in the Manifest File ... This error will go away. 

This error went away when i modified the Merged
Manifest file for RazorPay SDK ... but this is only a temporary solution. 

In order to fix this issue permanently you guys need to add `android:exported="false"` in your RazorPay manifest ... 

## Code example, screenshot, or link to a repository:
Please provide a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

![Screenshot from 2021-11-23 14-02-46](https://user-images.githubusercontent.com/10581266/142994185-6c18f91a-3a63-4d01-abce-28c7a1c18aff.png)
![Screenshot from 2021-11-23 14-03-00](https://user-images.githubusercontent.com/10581266/142994192-ae03e241-cef7-47be-bf67-8a9f4d8fcdfd.png)

**Comment by vivekshindhe** [comment]
@SumeetMoray This has been resolved in v1.6.17. Closing the ticket.
