### ISSUE TITLE
I am facing this error after integration can you please help for resolving this error

### ISSUE THREAD

**Issue by sunil456** [razorpay/razorpay-android-sample-app#279]
## Description

Please provide a clear and concise description of what the bug is. Include screenshots if needed.
Please test using the latest Razorpay Android SDK to make sure your issue has not already been fixed. 

## Razorpay SDK Version :
Open `build.gradle`. > com.razorpay:checkout:1.6.15

## Android OS Version :     compileSdkVersion 30
Any specific android version if this issue is only occuring on a specific version. 

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.

1.
2.

## Code example, screenshot, or link to a repository:
Please provide a link to a repository on GitHub, or provide a minimal code example that reproduces the problem.
You may provide a screenshot of the application if you think it is relevant to your bug report.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by vivekshindhe** [comment]
@sunil456 Please update to the latest version. 1.6.17. It's available on Maven Repository. Thank you. Closing this ticket for now.
