### ISSUE TITLE
I am facing this issue while building the app (target sdk id 31)

### ISSUE THREAD

**Issue by akashswipe04** [razorpay/razorpay-android-sample-app#282]
Razorpay's theme is causing this error in the manifest file. It's not letting me build with the default Checkout Theme of Razorpay.

`java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.`

**Comment by vivekshindhe** [comment]
@akashswipe04 You just need to use a theme which is a descendant of Theme.AppCompat for this to work. Or you can use Theme.Material and it's descendants.

**Comment by AdityaV025** [comment]
The solution is to override manifest settings of razorpay.

Add below lines in your AndroidManifest.xml file in order to override manifest settings of razorpay.

    <receiver
        android:name="com.razorpay.RzpTokenReceiver"
        android:exported="false">
        <intent-filter>
            <action android:name="rzp.device_token.share" />
        </intent-filter>
    </receiver>
    
    <activity
        android:name="com.razorpay.CheckoutActivity"
        android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
        android:exported="true"
        android:theme="@style/RazorpayTheme"
        tools:replace="android:theme">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <data
                android:host="rzp.io"
                android:scheme="io.rzp" />
        </intent-filter>
    </activity>

and We also have to replace the theme of CheckoutActivity in order to resolve further crashes, 

    tools:replace="android:theme

tag is important here, which has been mentioned above in manifest settings, now add below code to styles.xml.

     <style name="RazorpayTheme" parent="Theme.AppCompat.Dialog">
        <item name="android:windowActionBar">false</item>
        <item name="android:windowFrame">@null</item>
        <item name="android:windowIsFloating">true</item>
        <item name="android:windowIsTranslucent">true</item>
        <item name="android:windowNoTitle">true</item>
        <item name="android:windowBackground">@android:color/transparent</item>
        <item name="android:colorBackgroundCacheHint">@null</item>
        <item name="android:background">@android:color/transparent</item>
        <item name="android:windowCloseOnTouchOutside">false</item>
    </style>

hope this helps!

**Comment by vivekshindhe** [comment]
The additional AndroidManifest.xml details that was needed to be added before is not necessary now with the latest version 1.6.17. Please update to that. Let us know if there's anything we can help you with. Closing the ticket for now. Please feel free to reopen or add a comment here for further assistance
