### ISSUE TITLE
exception when release application

### ISSUE THREAD

**Issue by triosoftteam** [razorpay/razorpay-android-sample-app#293]
Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{in.triosoft.freschopsbar/com.razorpay.CheckoutActivity}: java.lang.IllegalArgumentException: Unknown color

**Comment by vivekshindhe** [comment]
This has been fixed in version 1.6.18. Please update. Feel free to create another issue if necessary. Thank you
