### ISSUE TITLE
Android 12 Manifest Merger Failed

### ISSUE THREAD

**Issue by vrone23** [razorpay/razorpay-android-sample-app#298]
Android 12 Running App shows error Manifest merger failed : android: exported needs to be explicitly specified for <activity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android: exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

I'm an Android App Developer so take suggestions from my answer below to short out this error soon.

**How to Fix:**
Merging Errors: Error: android: exported needs to be explicitly specified for element <activity#com.razorpay.CheckoutActivity>. Apps targeting Android 12 and higher are required to specify an explicit value for `android: exported` 

Please fix it as soon as possible because in the market Android 13 is coming soon and your SDK is not supported for Android 12.

**Comment by vivekshindhe** [comment]
@vrone23 this has been handled in version 1.6.18. Please update to that version.
