### ISSUE TITLE
Not compatible for android 12

### ISSUE THREAD

**Issue by kdsoni11** [razorpay/razorpay-android-sample-app#308]
**Exported Element issue**
Please add exported element in intent filter activity menifest file
I am not able to build application in latest adroid sdk without  this element
Please update with newer version 

**Older version 'com.razorpay:checkout:1.6.12'**

**Comment by vivekshindhe** [comment]
@kdsoni11 tested it with SDK 32. Seems to be working fine in version 1.6.20(latest)
