### ISSUE TITLE
changing to prefix phone number after failure payment.

### ISSUE THREAD

**Issue by nareshkatta99** [razorpay/razorpay-android-sample-app#31]
Hi,
When the user edits the prefix phone number and come backs after failure payment,
The phone number is coming back to prefix phone number only.
My tester is killing me to fix it :) 
Prefix phone number is 96525xxxxx, He edited that to 94910xxxxx.
![phone number 1](https://user-images.githubusercontent.com/7877291/27183068-f1e4549a-51fa-11e7-99cf-835aca32efff.jpg)

After he failed the payment,
![phone number 2](https://user-images.githubusercontent.com/7877291/27183150-45decc6a-51fb-11e7-9848-96a7e72acffe.jpg)

While selecting the payment bank
![phone number 3](https://user-images.githubusercontent.com/7877291/27183163-56b70958-51fb-11e7-8f99-ed9adb396156.jpg)

**Comment by akshaybhalotia** [comment]
@pronav Is this related to the sessions thing?

**Comment by pronav** [comment]
Thanks for reporting @Naresh-Katta. we'll fix it by monday.

**Comment by Naresh-Katta** [comment]
Hi there,
any update on this issue?
