### ISSUE TITLE
Accepting large phone numbers

### ISSUE THREAD

**Issue by Naresh-Katta** [razorpay/razorpay-android-sample-app#32]
Phone number is accepting more than 10 or 12 numbers.

![4449948798711520669-account_id 2](https://user-images.githubusercontent.com/7877291/27183326-dfcb3b92-51fb-11e7-9eda-19799b023c5c.png)

**Comment by akshaybhalotia** [comment]
@Naresh-Katta This is the expected behavior, the phone number could be any length upto 15 digits. For more info on phone number schemes, visit <https://en.wikipedia.org/wiki/Telephone_numbering_plan>.
