### ISSUE TITLE
Android App is Crashing while using  implementation 'com.razorpay:checkout:1.6.22'

### ISSUE THREAD

**Issue by tusharquantsapp** [razorpay/razorpay-android-sample-app#320]
We have implemented your latest dependency in our Android App 
" 'implementation 'com. razorpay:checkout:1.6.22' " **and after that, we are facing the following a crash above android 12**

OpinionatedSoln.kt line 99
com.razorpay.OpinionatedSoln.showDialog

Fatal Exception: java.lang.NullPointerException
null cannot be cast to non-null type kotlin.Boolean
java.util.Objects.requireNonNull (Objects.java:245)
com.razorpay.OpinionatedSoln.showDialog (OpinionatedSoln.kt:99)
com.razorpay.OpinionatedSoln.checkEnvVariablesForProject (OpinionatedSoln.kt:50)
com.razorpay.OpinionatedSoln.checkIfVersionUpdateExists$lambda-0 (OpinionatedSoln.kt:90)
com.razorpay.OpinionatedSoln.$r8$lambda$2u-MILbRY-RVpUqiCdvHUhh9kls (OpinionatedSoln.kt)
com.razorpay.OpinionatedSoln$$InternalSyntheticLambda$0$352559c431991928ba74d2dc041bdfbc8acdb9ff6cbf60ae2e43927eb2aba353$0.run (OpinionatedSoln.java:4)
com.razorpay.i_$z_.onPostExecute (Owl.java:5137)

**Comment by vivekshindhe** [comment]
Fixed in v1.6.23. Thank you for your patience.
