### ISSUE TITLE
Cancel payment methord Razorpay

### ISSUE THREAD

**Issue by longquangpham90** [razorpay/razorpay-android-sample-app#328]
Hi team development!
I have a issue with razorpay v1.6.24
`implementation 'com.razorpay:checkout:1.6.24'`
we cancel payment methord, but app show messesage error
can you help me create function cancel callback edit message or hide message
Thanks!
<img width="435" alt="Screen Shot 2022-09-26 at 16 21 01" src="https://user-images.githubusercontent.com/15273999/192240740-95a37eef-67b2-4242-bcff-222eed55cd29.png">

**Comment by vivekshindhe** [comment]
Is the onPaymentError method wrapped inside a try catch block? If not please add the try catch block and it should work fine. @longquangpham90

**Comment by longquangpham90** [comment]
@vivekshindhe yes we have use to with try-catch. But message always show toast. We can't remove message toast its

**Comment by vivekshindhe** [comment]
That toast message isn't shown if the code is wrapped in a try catch block. That's the error message. @longquangpham90

**Comment by longquangpham90** [comment]
oh thanks, we have update all action in try-catch block
That it ok
