### ISSUE TITLE
In Live mode for android integration before opening payment gateway opening SDK compatibility popup. Need to hide that popup.

### ISSUE THREAD

**Issue by AppristineMahesh** [razorpay/razorpay-android-sample-app#347]
@captn3m0 @shashankkumar @pronav @mb-14 @harshilmathur 

Below is my code and also attached screenshot.  Need to hide that popup in live mode. 

```
com.razorpay.Checkout checkout = new com.razorpay.Checkout();

        checkout.setKeyID("MY_LIVE_MODE_KEY");

        final Activity activity = this;

        try {
            JSONObject options = new JSONObject();

            options.put("name", "Marchant Name");
            options.put("description", description);
            options.put("order_id", orderid);
            options.put("currency", currency);
            options.put("amount", Amount);
            options.put("prefill.email", "User email address");
            checkout.open(activity, options);
        } catch (Exception e) {
            Log.e("paymenteception", "Error in starting Razorpay Checkout", e);
        }
```

![Screenshot_20230408_104718](https://user-images.githubusercontent.com/111556542/230715087-bb8252f5-fae6-4e91-ac73-e15c6718fcf6.jpg)

Thank You

**Comment by vivekshindhe** [comment]
@AppristineMahesh this won't be shown in release mode. This was developed to let you know if there's an update in only debug mode. You can also use the 'Hide Notification Forever' button to not see it.

**Comment by AppristineMahesh** [comment]
@vivekshindhe thank you for your response. Generated release mode this popup not showing. Closing this issue. Thank you...
