### ISSUE TITLE
Razorpay error case not working

### ISSUE THREAD

**Issue by maheshsystimanx** [razorpay/razorpay-android-sample-app#46]
How to handle error case in razorpay-android-sample-app?
I checked this code success case is working and also show the toast.
But in error case is not showing the toast. Please clarify my doubt.

Razor pay test key: rzp_test_X41hYj0GeeILH9

**Comment by hariramsvnit** [comment]
@maheshsystimanx 
1. If payment is successful, sdk gives callback in `onPaymentSuccess` method.
2. If there is any payment related error we show user option to retry.
3. If user choose to exist razorpay activity by clicking back button or by clicking cancel button on top right, sdk will give error callback in `onPaymentError`.

Do let me know if still have any doubts.

**Comment by Priyanshi-Z** [comment]
@hariramsvnit I want to avoid the retry option. In my case it is happening (In Live mode ) I have selected cards --> Added testing cards --> payment fails -->razor pay shows screen of payment fail (for around 2 seconds) --> then again card details has to be added (I don't want it). 

Just adding retry option is disabled while passing the payloads to razorpay. Could you help me on this too.
