### ISSUE TITLE
API key is invalid

### ISSUE THREAD

**Issue by gauravgupta566** [razorpay/razorpay-android-sample-app#47]
i have gone through merchant panel and copy security api key and pasted it into manifest file then why I am getting this error, which is correct api key

**Comment by hariramsvnit** [comment]
@gauravgupta566  You need to put the key id in the manifest, which will start with `rzp_test` or `rzp_live`.

**Comment by gauravgupta566** [comment]
how to get that id , I go through merchant panel and i have seen only security key. I have not seen any key which is started by rzp_test or rzp_live

**Comment by hariramsvnit** [comment]
@gauravgupta566 You can follow these simple steps in this short animation to generate API keys: https://i.imgur.com/ylwYzbC.gif

**Comment by gauravgupta566** [comment]
there is no option for setting , now panel is so different

**Comment by gauravgupta566** [comment]
http://205.147.110.100:8080/integrationdashboard/
this link is not working ,these link are given by mobikwik

**Comment by Mayur-Wadpalliwar** [comment]
@gauravgupta566 This is `Razorpay payment gateway` and not `Mobikwik`. Please contact mobikwik for the same.

**Comment by gauravgupta566** [comment]
sorry sir,

On Mon, Jan 22, 2018 at 8:26 PM, Mayur Wadpalliwar <notifications@github.com
