### ISSUE TITLE
Activity code listener ambiguity

### ISSUE THREAD

**Issue by shubhamrai1993** [razorpay/razorpay-android-sample-app#48]
Can you please mention in the PaymentActivity that the activity must be the listener as well in order for the checkout flow to work. It's not very obvious.

**Comment by hariramsvnit** [comment]
@shubhamrai1993 We have mentioned in the [doc](https://docs.razorpay.com/v1/page/android-checkout-sdk-v14x#section-basic-usage) that your activity need to implement `PaymentResultListener` to receive the callbacks.
