### ISSUE TITLE
onPaymentSuccess and onPaymentFailure callbacks in fragments?

### ISSUE THREAD

**Issue by goonerDroid** [razorpay/razorpay-android-sample-app#5]
my current implmentation in fragment is:-

` private void startRazorPayPayment(PassportCardsBean passportCardsBean) {
        final String public_key = "sdfsdfsdfsdf";
        final String PAYMENTLOGOURL = String.valueOf(getResources().getDrawable(R.drawable.footlogo));
        final Checkout co = new Checkout();
        co.setPublicKey(public_key);

        try{

            JSONObject options = new JSONObject("{" +
                    "description:" + "'"+passportCardsBean.getAppDesc()+"\',"+
                    "image:"+"'"+PAYMENTLOGOURL+"\'," +
                    "currency: 'INR'}"
            );

            options.put("amount", passportCardsBean.getPrice() * 100);
            options.put("name",  passportCardsBean.getAppTitle());
            options.put("prefill", new JSONObject("{email:" + "'"+Utils.getUserEmail(activity)+"\'," +
                    " contact:" + "'"+Utils.getUserContact(activity)+"\'}"));

            co.open(activity, options);

        } catch(Exception e){
            Toast.makeText(activity, e.getMessage(), Toast.LENGTH_SHORT).show();
            e.printStackTrace();
        }
    }

    /**
     * The name of the function has to be
     *   onPaymentSuccess
     * Wrap your code in try catch, as shown, to ensure that this method runs correctly
     */
    public void onPaymentSuccess(String razorpayPaymentID){
        try {
            Toast.makeText(activity, "Payment Successful: " + razorpayPaymentID, Toast.LENGTH_SHORT).show();
        }
        catch (Exception e){
            Log.e("com.merchant", e.getMessage(), e);
        }
    }

    /**
     * The name of the function has to be
     *   onPaymentError
     * Wrap your code in try catch, as shown, to ensure that this method runs correctly
     */
    public void onPaymentError(int code, String response){
        try {
            Toast.makeText(activity, "Payment failed: " + Integer.toString(code) + " " + response, Toast.LENGTH_SHORT).show();
        }
        catch (Exception e){
            Log.e("com.merchant", e.getMessage(), e);
        }
    }`

on Back press from webView Client i get a toast message showing onPaymentError is not impleneted! 

Should i use this in activity instead of an fragment?? Help

**Comment by shashankmehta** [comment]
Yes, the `onPaymentSuccess` and `onPaymentError` methods need to be defined in the parent `activity`. The payment start method can be anywhere, as long as you are passing the correct `activity` context. I'll expressly mention this in the documentation too. Sorry for the confusion.

**Comment by shashankmehta** [comment]
This has been added to the documentation too, available [here](https://docs.razorpay.com/v1/page/android-sdk-v0100). Feel free to reopen this issue in case there's still a problem.

**Comment by goonerDroid** [comment]
Thanks!Also have some problem regarding theme as well,should i open a new issue or is it cool in this thread?

**Comment by shashankmehta** [comment]
Going by GitHub guidelines, it should be a new issue, but we can discuss here too :)

As per the mail, you want to use theme color feature in Android SDK, right? This is the code in the mail:
`options.put("theme",new JSONObject("{color: '8f3222b'}")); `

This should be:
`options.put("theme",new JSONObject("{color: '#8f3222'}")); `

The changes:
- The color value should be a valid html color setting.
- Hexadecimal color should start with `#`
- Hexadecimal color is only 6 characters long. In the sample code it was 7.

Feel free to correct me if the issue was something else.

**Comment by goonerDroid** [comment]
Thanks please ignore the last mail!

**Comment by shashankmehta** [comment]
Will do :)

**Comment by HarshavardhanK** [comment]
@shashankmehta how do I access payment_signature as in the web checkout integration?

**Comment by pronav** [comment]
Method signature of `onPaymentSuccess` has been overloaded - it now returns another parameter containing signature if you're using razorpay orders api. See https://razorpay.com/docs/payment-gateway/orders/migration/#checkout-on-android for details.

**Comment by 52280** [comment]
sir, I am implementing Razor pay in fragment then how to pass current reference activity to the checkout page in android. guide me it more than 5 days. I have already raise the same issues.
my code is like: 
 final RepaymentFragment repaymentFragment = this;

        final Checkout checkout = new Checkout();
        checkout.setKeyID("rzp_test_xmfEfhhhgsIpkOoTR");

        //checkout.setImage(R.drawable.logo);

         try {
             JSONObject options = new JSONObject();
         options.put("name", "vijay");
         options.put("description", "123456");
         options.put("image", "https://s3.amazonaws.com/rzp-mobile/images/rzp.png");
         options.put("order_id", "9A33XWu170gUtm");
         options.put("currency", "INR");
         options.put("amount", "500");

         JSONObject prefill = new JSONObject();
         prefill.put("email","appsbuilder941@gmail.com");
         options.put("prefil",prefill);
         //options.put("theme",new JSONObject("#8f3222"));

         checkout.open(repaymentFragment.getActivity(),options);

         }
         catch(JSONException e) {
             e.printStackTrace();

             Log.e(TAG, "Error in starting Razorpay Checkout", e);
             Toast.makeText(getActivity(),"Error in payment"+e.getMessage(),Toast.LENGTH_LONG).show();

         }
    }

    @Override
    public void onPaymentSuccess(String s) {
        Toast.makeText(getContext(),"Loading sucess",Toast.LENGTH_LONG).show();

    }

    @Override
    public void onPaymentError(int i, String s) {
        Toast.makeText(getContext(),"Loading failed",Toast.LENGTH_LONG).show();

    }

guide me on my mail id : appsbuilder941@gmail.com for android

**Comment by vasudev4689** [comment]
dd

**Comment by Aravindh1505** [comment]
We have to use onPaymentSuccess and onPaymentError in MainActivity if you are using fragments.

**Comment by karun02525** [comment]
Hi,
I am trying to implement android Razorpay SDK everything is a success but I am facing failures in response it does not call errors methods.

I'm using a callback interface with PaymentResultWithDataListener instead of PaymentResultListener.

Please update me quickly.
