### ISSUE TITLE
Get transaction details

### ISSUE THREAD

**Issue by neopraveen** [razorpay/razorpay-android-sample-app#51]
How to pass transaction id and get Transaction details like - Mode of Payment, Transaction ID etc.

**Comment by AbhinavArora95** [comment]
Hi, the sdk doesn't have this functionality. You need to do this at your end by making an api call. Please refer to - https://docs.razorpay.com/docs/v1paymentsid

**Comment by iAmAndroidDeveloper** [comment]
on https://api.razorpay.com/v1/payments/payment_id  its not working ,

how to get like bellow response ?

{
  "count": 2,
  "entity": "collection",
  "items": [
    {
      "id": "pay_7IZD7aJ2kkmOjk",
      "entity": "payment",
      "amount": 500,
      "currency": "INR",
      "status": "captured",
      "order_id": null,
      "invoice_id": null,
      "international": false,
      "method": "wallet",
      "amount_refunded": 0,
      "refund_status": null,
      "captured": true,
      "description": "Purchase Description",
      "card_id": null,
      "bank": null,
      "wallet": "freecharge",
      "vpa": null,
      "email": "a@b.com",
      "contact": "91xxxxxxxx",
      "notes": {
        "merchant_order_id": "order id"
      },
      "fee": 12,
      "tax": 2,
      "error_code": null,
      "error_description": null,
      "created_at": 1487348129
    }

**Comment by Mayur-Wadpalliwar** [comment]
@iAmAndroidDeveloper To get the above response, you need to call https://api.razorpay.com/v1/payments/payment_id  API from a **backend server** once you get the razorpay_payment_id as a response to a successful payment in the onPaymentSuccess handler in android

**Comment by Mayur-Wadpalliwar** [comment]
@iAmAndroidDeveloper You need to pass the pay_AktITrIGYzKkdp to your Backend server from Android and then use this API 
curl -u YOUR_API_KEY:YOUR_API_SECRET \ 
https://api.razorpay.com/v1/payments/pay_AktITrIGYzKkdp to fetch the details

**Comment by iAmAndroidDeveloper** [comment]
thanks buddy! you save my days
