### ISSUE TITLE
Compatibility problems 

### ISSUE THREAD

**Issue by rajivenator** [razorpay/razorpay-android-sample-app#55]
```
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

I get the error like this :
Process 'command '/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
```

If these are set then the application does not even compile.
Using Android Studio 3.1.2
I tried this on the sample app as well as my existing app.
We need to integrate razor pay with our app but unfortunately the above issue is restricting me.

**Comment by hariramsvnit** [comment]
@rajivenator Can you please try solution suggested here(https://github.com/razorpay/razorpay-android-sample-app/issues/50#issuecomment-379996496)
