### ISSUE TITLE
Support for maven/jcenter repository

### ISSUE THREAD

**Issue by thekalinga** [razorpay/razorpay-android-sample-app#6]
Currently there is no way to include the repository without copying the jar into the project source.

Can u upload the artifact to maven/jcenter, so that we don't need to include it manually in the project (+ our source repo will not be polluted)

Currently, to avoid including the file in the source control

1. I am installing the artifact into the local maven repository using shell

```sh
mvn install:install-file -Dfile=razorpay-android-0.11.1.jar -DgroupId=com.razorpay -DartifactId=android -Dversion=0.11.1 -Dpackaging=jar
```

2. Referencing the artifact from the gradle by adding

```gradle
repositories {
    mavenLocal() // <- will point to local maven repository
    jcenter()
}
```

3. Referencing the dependency in `app.gradle`

```gradle
dependencies {
    // A lot more dependencies
    compile 'com.razorpay:android:0.11.1'
}
```

If you fix this issue, everyone can just point to jcenter and be done with instead of hacks

**Comment by steelrooter** [comment]
We are going to release the next version of our SDK on Maven Central too.

**Comment by hariramsvnit** [comment]
We have started distributing razorpay sdk by maven central repository. You can 
refer our documentation of [v1.0.1](https://docs.razorpay.com/v1/page/android-sdk-v10x) for more info.
