### ISSUE TITLE
checkout form close call

### ISSUE THREAD

**Issue by sachinvelaga** [razorpay/razorpay-android-sample-app#60]
I have a use case for a kiosk app where if someone abandons the payment after opening checkout form, i have to close the form and exit the payment after an interval.Closing the form manually by clicking the 'x' on the form provides call back to payment error where an error view can be set. 

In case of using a countdown timer, if i change the view  after timer finishes, the checkout form still lurks on the top.  the only way is to destroy the activity but in that case, the soft keyboard is left open which i have to handle separately. Also  if i provide method as upi into checkout form, the text box doesn't get focus automatically and keyboard doesn't open. 

Can i know what can be done here?

**Comment by Mayur-Wadpalliwar** [comment]
Hello @sachinvelaga,

Please try passing an additional param to Razorpay checkout options as `timeout`. The value of this param shall be in seconds.

So for `timeout: 2` checkout will be closed automatically after 2 seconds
