### ISSUE TITLE
`order_id` creating issue

### ISSUE THREAD

**Issue by prithvibhola** [razorpay/razorpay-android-sample-app#62]
When `order_id` is used in JSONObject of options, Razorpay SDK is throwing an error and moves into onPaymentError method

private fun startPayment(orderId: Long, paymentGateway: PaymentGateway) {
        val checkout = Checkout()
        checkout.setImage(R.drawable.lifcare_logo)
        checkout.setFullScreenDisable(true)
        try {
            val options = JSONObject()
            options.put("name", "Name")
            options.put("description", "Description")
            options.put("currency", "INR")
            options.put("amount", paymentGateway.amount.times(100))
            options.put("order_id", paymentGateway.refTransactionId)

            val prefill = JSONObject()
            prefill.put("email", "emailID")
            prefill.put("contact", "9999999999")
            prefill.put("method", "card")

            options.put("prefill", prefill)
            options.put("theme", JSONObject("{color: '#7cb342'}"))
            checkout.open(this, options)
        } catch (e: Exception) {
            Timber.e(e, "Cannot pay right now!!")
        }
    }

**Comment by yashodhandivakaran** [comment]
@prithvibhola 

You need to send an order id which has been created by calling Razorpay API. You can refer our Orders API doc here(https://docs.razorpay.com/page/orders).
