### ISSUE TITLE
How to Close RazorPayActivity in Android

### ISSUE THREAD

**Issue by saisasanksunkavalli** [razorpay/razorpay-android-sample-app#64]
I am opening the RazorPay Payment Screen using the below code.
`final Checkout co = new Checkout();`
`co.open(activity, options);`

There is no option for me to Close the Payment Screen dynamically in Android, that option is provided in ios using the _.close()_ method.

**Comment by amychaudhary** [comment]
I am facing the same issue. Did u get any solution to it?

**Comment by saisasanksunkavalli** [comment]
I used a workaround for it , I am using a **timeout** of 10 minutes while passing the options to the SDK. If the RazorPay View is open for 10 minutes , it will finish the RazorPayActivity. You can send the timeout in seconds using the RazorPay Options.

**Comment by saisasanksunkavalli** [comment]
On the Change of colour of the timer bar , you need to check their JS SDK . Thats how i came to know about the "timeout" parameter. Everything is not documented.
As far as i know , there is no listener for the timeout.

**Comment by udaynplay** [comment]
if there is no listener for the timeout how to handle it.
