### ISSUE TITLE
Library not completely install

### ISSUE THREAD

**Issue by ArvindMewada** [razorpay/razorpay-android-sample-app#67]
1.  compile project(name: "razorpay-android-3.4.0", ext: 'aar')
 
-   Required keys [path] are missing from map {name=razorpay-android-3.4.0, ext=aar}.

**Comment by hariramsvnit** [comment]
@ArvindMewada Please refer this(https://stackoverflow.com/questions/16682847/how-to-manually-include-external-aar-package-using-new-gradle-android-build-syst) link for how to include aar file into the project
