### ISSUE TITLE
Android SDK: onPaymentError doesn't provide arguments to extract paymentID

### ISSUE THREAD

**Issue by joshiashish** [razorpay/razorpay-android-sample-app#68]
Just like onPaymentSuccess, is there a way to extract paymentID for onPaymentError? We would like to track it for every failure and map it to a user account in our backend.

**Comment by hariramsvnit** [comment]
@joshiashish The Android SDK doesn't provide payment id of failed payments, but your backend can fetch it by calling Razorpay API.
