### ISSUE TITLE
Paytm Wallet Click 

### ISSUE THREAD

**Issue by imrankhanluhar** [razorpay/razorpay-android-sample-app#71]
Paytm  wallet button click is not working after creating Release build in android. Please solve the this problem , we have getting to much business loss .

**Comment by hariramsvnit** [comment]
@imrankhanluhar We are looking into it.

**Comment by imrankhanluhar** [comment]
i have looked in some android application they do not redirect to outside the razor pay and does the payment as other wallet like PayZapp , Ola Money .


i have attached one application screenshot they does not redirect to outside and get payment in razor pay sdk 

https://user-images.githubusercontent.com/6330249/43135513-4d5ed9c0-8f63-11e8-9e3a-ee5abc0ee0a2.png
https://user-images.githubusercontent.com/6330249/43135514-4d943e6c-8f63-11e8-94bc-34587f226b31.png

**Comment by imrankhanluhar** [comment]
Your technical team today say it's not because of us . it's problem due to paytm . 
and goes away

**Comment by hariramsvnit** [comment]
Has the discussion over chat, closing it.

**Comment by imrankhanluhar** [comment]
hello , this issues is updated or not now can we user paytm now in wallet

**Comment by imrankhanluhar** [comment]
hi its not update yet

**Comment by imrankhanluhar** [comment]
hi hariramsvnit , is this problem solved . can we used paytm now

**Comment by imrankhanluhar** [comment]
hi hariramsvnit , is this problem solved . can we used paytm now as wallet

**Comment by Madhur6** [comment]
Hii, I am facing this problem now in Paytm.
How did u resolve it, please help
