### ISSUE TITLE
Problem installing the SDK on Android Studio 3.1.3

### ISSUE THREAD

**Issue by TdevM** [razorpay/razorpay-android-sample-app#74]
Can't install checkout SDK by adding 
`implementation('com.razorpay:checkout:1.4.9')` or 
`compile('com.razorpay:checkout:1.4.9')` to build.gradle

Fails with `Process 'command 'C:\Program Files\Java\jdk1.8.0_181\bin\java.exe'' finished with non-zero exit value 1`
 
app details

` compileSdkVersion 27`
    `buildToolsVersion '27.0.3'`
`supportLibraryVersion = '27.1.1'`
`Gradle Version 4.4`
`Android Plugin Version 3.1.3`

**Comment by hariramsvnit** [comment]
@TdevM Can you provide full error? Also, I hope you are not using jack options.

**Comment by hariramsvnit** [comment]
@prakhar1001 try adding `android.enableD8.desugaring = true` to `gradle.properties` file

**Comment by anantshah93** [comment]
Same issue

**Comment by hariramsvnit** [comment]
Also have look at https://github.com/razorpay/razorpay-android-sample-app/issues/50, it might help.

**Comment by anantshah93** [comment]
android.enableD8.desugaring = true solved issue thanks
