### ISSUE TITLE
how to set api key dynamically?

### ISSUE THREAD

**Issue by abhinay-w3bminds** [razorpay/razorpay-android-sample-app#75]
Normally we are setting api key in manifest but is there any way to set api key dynamically

**Comment by Mayur-Wadpalliwar** [comment]
@abhinay-w3bminds You can use the checkout.setKeyID method. You can ignore the deprecation warning for this method.

**Comment by sachinharne** [comment]
I have used     implementation 'com.razorpay:checkout:1.5.13'

And set the key like this : 
Checkout checkout = new Checkout();
checkout.setKeyID(MY_KEY_HERE);

Still its asking me to use the key in Manifest. What should i do ? I want to set it dynamic.

Please help.
