### ISSUE TITLE
disable fields when prefilled

### ISSUE THREAD

**Issue by shashkiranr** [razorpay/razorpay-android-sample-app#76]
Hi Team,

I would like to know if there is a way to disable the email and phone number fields when pre filled in checkout in android.  

version : com.razorpay:checkout:1.4.9

**Comment by Mayur-Wadpalliwar** [comment]
@shashkiranr You can create a json object for “readonly” and put values as below,

email: true
contact: true

**Comment by shashkiranr** [comment]
Hi Mayur,

Can you kindly update me as to the correct way.

**Comment by shashkiranr** [comment]
Did not work, I am still able to edit the fields

**Comment by Mayur-Wadpalliwar** [comment]
@shashkiranr The below is working for me,

```
JSONObject ReadOnly = new JSONObject();
ReadOnly.put("email", "true");
ReadOnly.put("contact", "true");

options.put("readonly", ReadOnly);
```

**Comment by Prashankumar** [comment]
Where to add this code?

**Comment by Mayur-Wadpalliwar** [comment]
You can add this in the checkout options along with other params

**Comment by KhyatiMehta3** [comment]
Hi, Is there anyway to get rid of the email field?

**Comment by deathstroke007** [comment]
How to hide the email Options like what happened in bounce Application. There is no field to enter the mail id only the number. Plus, is there a way to make the email optional?

**Comment by hopetechnologies** [comment]
How to make phone and email as optional... I don't want my customers to enter their phone and email before paying... Is there any option to disable it.

**Comment by thangmam** [comment]
hello , i am also wondering if its possible to make phone and email optional so that my user can directly choose payment option.

**Comment by deathstroke007** [comment]
You can create a JSONObject Prefill and send it via options like the code below : 
 
```
JSONObject preFill = new JSONObject();
            preFill.put("email", "");
            preFill.put("contact", "");
            preFill.put("name", "");
            // To directly open the card Entering screen.
            // options - card / netbanking / wallet / emi / upi
            preFill.put("method", "card");
options.put("prefill", preFill);
```

**Comment by avinashk369** [comment]
final Checkout co = new Checkout();

        try {
            JSONObject preFill = new JSONObject();
            preFill.put("email", "");
            preFill.put("contact", "");

            JSONObject options = new JSONObject();
            options.put("name", "XXXXXXXXXXX");
            options.put("prefill", preFill);
            options.put("description", "Payment process");
            //You can omit the image option to fetch the image from dashboard
            options.put("image", "https://s3.amazonaws.com/rzp-mobile/images/rzp.png");
            options.put("currency", "INR");
            options.put("amount", "100");

            co.open(activity, options);
        } catch (Exception e) {
            Toast.makeText(activity, "Error in payment: " + e.getMessage(), Toast.LENGTH_SHORT)
                    .show();
            e.printStackTrace();
        }

i tried this but did not work.
any help and suggestion would be appreciated

**Comment by avinashk369** [comment]
> @shashkiranr The below is working for me,
> 
> ```
> JSONObject ReadOnly = new JSONObject();
> ReadOnly.put("email", "true");
> ReadOnly.put("contact", "true");
> 
> options.put("readonly", ReadOnly);
> ```

not working in 
com.razorpay:checkout:1.5.13
@authour may reopen this issue

**Comment by sandeepmaaram** [comment]
This should work. use **readonly** instead of **readOnly**

**Comment by sandeepmaaram** [comment]
Below code should work

```
JSONObject readonly = new JSONObject();
readonly .put("email", "true");
readonly .put("contact", "true");

options.put("readonly", readonly );
```

I have tested with `com.razorpay:checkout:1.5.13`

**Note:** Just for kind information use key as  **readonly** instead of **readOnly** in `options` JSONObject

**Comment by santosh3700** [comment]
This is working like this. 
Inside the **option** variable just create the JSON yourself

`const options = {
   //other data
    prefill: {
        //prefill data
    },
  
    readonly: {
    	email: true,
    	contact: true
    }
};`

**Comment by KhyatiMehta3** [comment]
Hi Santosh
Thank you very much for getting back on this thread. I will try it out and
get back to you!

Thanks & Best Regards,
Khyati.

**Comment by mpnihad** [comment]
The position where 

JSONObject readonly = new JSONObject();
readonly .put("email", "true");
readonly .put("contact", "true");

options.put("readonly", readonly );  

this code is added matters when i put them below the prefill it worked 
or try putting it at the end

**Comment by MohanReddy999** [comment]
Hi Team
I'm using python-Django. I tried below way but still my payment page shows the editable email and phone number and also pre-fill is not working. The details are getting from the first time when we enter them.
`<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
	var options = {

	// Enter the Key ID generated from the Dashboard
	key: "{{ razorpay_merchant_key }}",
	amount: "{{ razorpay_amount }}",
	currency: "INR",

	// Your/store name.
	name: "dummy project",

	// Pass the `id` obtained in the response of Step 1
	order_id: "{{ razorpay_order_id }}",
	callback_url: "{{ callback_url }}",
	prefill: {
                   email: "abc@gmail.com",
                   contact: "8143888888"
              },
    readonly: { email: true, contact: true },
	};

	// initialise razorpay with the options.
	var rzp1 = new Razorpay(options);

	
	document.getElementById("pay-btn").onclick = function (e) {
	rzp1.open();
	e.preventDefault();
	};

</script>
`
