### ISSUE TITLE
Payment stuck on Redmi device while loading bank page

### ISSUE THREAD

**Issue by CHIRANJIT1988** [razorpay/razorpay-android-sample-app#77]
Hi,
Payment stuck while loading bank page using live credential. Below is the device details and screenshot:

![screenshot_2018-09-05-12-57-33-181_com doconline doconline](https://user-images.githubusercontent.com/15885223/45353832-9e1c8500-b5d9-11e8-9c87-2cca1ef28e92.png)

Device Name - Redmi
Model No - 3S
Android Version 6.0.1MMB29M

**Comment by Mayur-Wadpalliwar** [comment]
@CHIRANJIT1988 Could you please download our android sample app on that device and try a payment and see if you are able to reproduce the same?

**Comment by CHIRANJIT1988** [comment]
@Mayur-Wadpalliwar Yes i have downloaded your SDK and i have tested with both test and live credential on the same device. Issue exists. Screenshot of sample SDK

![screenshot_2018-09-11-15-35-01-636_com razorpay newsampleapp](https://user-images.githubusercontent.com/15885223/45354532-74fcf400-b5db-11e8-8463-4b3c732a751c.png)

**Comment by CHIRANJIT1988** [comment]
@Mayur-Wadpalliwar Any update on this issue ? Why this is happening.

**Comment by Mayur-Wadpalliwar** [comment]
@CHIRANJIT1988 We are trying to re-produce this on a redmi device. Shall keep you posted on the update.

**Comment by CHIRANJIT1988** [comment]
@Mayur-Wadpalliwar Thanks for the update. I have found that issue on that specific redmi device only.

**Comment by AbhinavArora95** [comment]
@CHIRANJIT1988 We are not able to re-produce this on redmi note devices.

Could you please try this on other latest redmi devices and let us know if the issue still persists there?

**Comment by ashokrawat15** [comment]
Hi,

I'm seeing the same payment issue with my Moto G (3rd generation) device running Android version 6.0.1. I can consistently reproduce the issue. Can someone plz suggest/help here to resolve this issue.

**Comment by DevPrash** [comment]
Hi,
Same issue exist in 
Ticket #: 289213

Followed Razorpay SDK setup documents:

**1. Razorpay Android SDK 1.4.9,1.4.8**

	Supported Min SDK version: 19
	**Issues exist in**

	Karbon A6 Turbo 
	•	Version – 19
	•	Android -4.4.2

	Intex cloud
	•	Version – 23
	•	Android -6.0

**2. Razorpay SDK version to 1.4.7**

	Supported Min SDK version bellow 19
	
	**Issues exist in**

	Karbon A6 Turbo 
	•	Version – 19
	•	Android -4.4.2

	Intex cloud
	•	Version – 23
	•	Android -6.0

**Comment by sumedht** [comment]
@CHIRANJIT1988 @DevPrash We have fixed this issue. If u still facing this plz update to our latest sdk v1.5.5

**Comment by sushmitha-mk** [comment]
Razorpay SDK version to 1.4.7

Device : Karbon
Android version: 4.4.2
model number: A6 Turbo

Not able to do the payment by using net banking(not displaying the list of banks properly), wallet(ola payments) and UPI(Not displaying  related apps such as google pay, phonepe, etc) methods

![image1](https://user-images.githubusercontent.com/45754519/56203350-aa325e80-6062-11e9-9fda-0236b221e282.jpeg)
![image2](https://user-images.githubusercontent.com/45754519/56203351-aacaf500-6062-11e9-9855-c41ab3d423a3.jpeg)
![image3](https://user-images.githubusercontent.com/45754519/56203352-aacaf500-6062-11e9-80c9-350fe3228fdb.jpeg)
