### ISSUE TITLE
Refund

### ISSUE THREAD

**Issue by SatyajeetRameena** [razorpay/razorpay-android-sample-app#78]
I have Booked My tickets on IRCTC application through Razorpay Option. According to IRCTC they have transfered amount on 1st of sept. but it is not being credited to my account yet.
kindly look after it.
Transaction ID - 100001420499247
Ticket ID - 1480968
Refund reference no. - rfnd_AsYNiQc3KFtQ5L

**Comment by emailsubjekt** [comment]
Have you had any further problems with this?

**Comment by SatyajeetRameena** [comment]
No. Thank you for helping me out.

**Comment by sumedht** [comment]
Closing this issue due to no response from your side. Please feel free to either re-open the issue or create a new issue if you have any additional queries.
