### ISSUE TITLE
UPI payment page get blank

### ISSUE THREAD

**Issue by sumit007** [razorpay/razorpay-android-sample-app#79]
Unable to make payment through UPI in Android app. When Users selects payment option as UPI and proceeds, The page goes blank. [Watch video](https://drive.google.com/file/d/1zCbOf9ZVgj6jCNpnD-OAgafiRJUIEQf2/view?usp=sharing).

Checkout SDK version we are using - v1.4.9 and also tried with v1.4.7

Device with problem 

One plus oxygen os
Redmi 2014818 Android Kitkat 4.4.4

**Comment by sumedht** [comment]
@sumit007 still facing this issue?our latest version of sdk is v1.5.5

**Comment by sumit007** [comment]
@sumedht this is fixed. Thank you.
