### ISSUE TITLE
How to disable only some payment modes in Razorpay UI

### ISSUE THREAD

**Issue by Dineshchitta** [razorpay/razorpay-android-sample-app#81]
Hey ,

* I want to show / hide only some payment modes like Netbanking , Wallets etc in Razorpay UI
* And In different payment modes I want to show / hide only some options For ex : I want to Hide paytm in wallet payment mode & I want to show Paytm in UPI mode

First of All Can we configure like this ? If yes how to configure 

TIA

**Comment by Mayur-Wadpalliwar** [comment]
@Dineshchitta You can drop an email to support@razorpay.com asking to disable the payment methods.

Also, Razorpay doesn't support paytm wallet

**Comment by Dineshchitta** [comment]
Hi @Mayur-Wadpalliwar  Thanks for the reply. Can we do this dynamically ? For Example user applied a coupon where that coupon applies for only one wallet. So based on the coupon / user can we put options dynamically. 

You can refer below image 

![image](https://user-images.githubusercontent.com/11161863/46287934-cf1d2380-c5a1-11e8-9d70-0780d5b57008.png)

**Comment by Mayur-Wadpalliwar** [comment]
@Dineshchitta You can enable / disable the payment methods dynamically however, it is not possible have control over each entity inside the payment method. For example, it is not possible to dynamically choose the corresponding wallet.

**Comment by Mayur-Wadpalliwar** [comment]
@Dineshchitta However, we have a different solution here which lets you customize the UI where you can have this control but the same comes under our enterprise plan solution: https://razorpay.com/pricing/

Do let us know if you want to explore that and we can arrange a call from our Business development team.

**Comment by swatiagarwal8586** [comment]
how to enable / disable the payment methods dynamically? what code i have to write for hiding all payment methods except to card payment method only.

**Comment by Mayur-Wadpalliwar** [comment]
@swatiagarwal8586 you can use `method` param to handle this,
```
method: {
    netbanking: true,
    card: true,
    wallet: true,
    upi: true
  },
```

**Comment by Pragna-zealous** [comment]
@Mayur-Wadpalliwar 
Thanks for this comment. It helps me to find solution. There is one issue that when I use as below,  logo hide from the checkout popup.
`method: {
    netbanking: false,
    card: true,
    wallet: false,
    upi: false
  },`

**Comment by Mayur-Wadpalliwar** [comment]
@Pragna-zealous Can you upload the logo on the Razorpay dashboard and remove  options.put("image", "https://s3.amazonaws.com/rzp-mobile/images/rzp.png"); from your code and try once?

**Comment by Pragna-zealous** [comment]
@Mayur-Wadpalliwar Yea now the logo display in checkout popup.
I have removed the image parameter and upload logo in razorpay settings tab.
Thank You.

**Comment by sankar-gp** [comment]
> `method`

how can i do it in android?

**Comment by cw-gawdeprasad** [comment]
Can I do this enabling and disabling of payment options via RazorPay dashboard? I would like to disable certain payment options and I have the Standard plan.

**Comment by akshay-rirev** [comment]
> @swatiagarwal8586 you can use `method` param to handle this,
> 
> ```
> method: {
>     netbanking: true,
>     card: true,
>     wallet: true,
>     upi: true
>   },
> ```

I need to block specific UPI payment, like google_pay How to do that

**Comment by vivek8417** [comment]
I need to block specific UPI payment, like google_pay How to do that

**Comment by sahilit** [comment]
> @swatiagarwal8586 you can use `method` param to handle this,
> 
> ```
> method: {
>     netbanking: true,
>     card: true,
>     wallet: true,
>     upi: true
>   },
> ```

How to hide EMI options

**Comment by virenpankaj222** [comment]
> > @swatiagarwal8586 you can use `method` param to handle this,
> > ```
> > method: {
> >     netbanking: true,
> >     card: true,
> >     wallet: true,
> >     upi: true
> >   },
> > ```
> 
> How to hide EMI method

 method: {
> >     netbanking: true,
> >     card: true,
> >     wallet: true,
> >     upi: true,
emi:false
> >   },

**Comment by xirainfotech** [comment]
> @swatiagarwal8586 you can use `method` param to handle this,
> 
> ```
> method: {
>     netbanking: true,
>     card: true,
>     wallet: true,
>     upi: true
>   },
> ```

Hey thanks this worked in Flutter as well.
emi:false to turn off emi options.
How to disable Pay Later option?

**Comment by junaidfkhan786** [comment]
how to hide pay later option

**Comment by ppv94** [comment]
How to hide pay later option 
```
    method: {
      netbanking: false,
      card: true,
      wallet: false,
      upi: true,
      paylater: false
    },
```
This doesn't work

**Comment by KrishanMac** [comment]
> @swatiagarwal8586 you can use `method` param to handle this,
> 
> ```
> method: {
>     netbanking: true,
>     card: true,
>     wallet: true,
>     upi: true
>   },
> ```

how do I put in android . Should I put it inside a JSONObject if so then how , can you please explain it . I want to disable some payment options like PayLater , EMI etc from the CheckOut UI . Since its my first time implementing it I'm kind of confused and the doc. is not clear as well for me . So can you please help it out .

**Comment by jaydeep-aipl** [comment]
how to hide wallet option (like hide to paypal)

**Comment by vishnutsatheesh** [comment]
I want to hide this Razorpay Wallet option, only in case of only while loading money to the wallet. How I can do it? @Mayur-Wadpalliwar 

![image](https://github.com/razorpay/razorpay-android-sample-app/assets/7602048/0e946f93-332b-41ef-b874-5cf284471fb6)

**Comment by vivekshindhe** [comment]
@vishnutsatheesh You can use the configuration options to set the UI to display whatever options you need. Docs [link](https://razorpay.com/docs/payments/payment-gateway/web-integration/standard/configure-payment-methods/)
