### ISSUE TITLE
Android Java 8 is not Support

### ISSUE THREAD

**Issue by androidreport** [razorpay/razorpay-android-sample-app#82]
Hi 
rezorpay lib is not supported  in java 8. Please check this.

See this- 

 implementation 'com.razorpay:checkout:1.4.9' 

 compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

 minSdkVersion 22
            targetSdkVersion 26
            versionCode 4

Error Show

Process 'command 'C:\Program Files\Java\jdk1.8.0_181\bin\java.exe'' finished with non-zero exit value 1

**Comment by Mayur-Wadpalliwar** [comment]
@androidreport Please refer https://github.com/razorpay/razorpay-android-sample-app/issues/74
