### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by Sunaina015** [razorpay/razorpay-android-sample-app#83]
Team, 
  I am getting a crash on -
//Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
com.razorpay.B_$q$.R$$r_

  com.razorpay.B_$q$.R$$r_ (Unknown Source:18076)
Please provide me the solution of this issue

**Comment by sumedht** [comment]
@Sunaina015 Have fixed this issue in v1.5.4 Update to latest
