### ISSUE TITLE
Doesn't timeout if stayed in payment page for a long time

### ISSUE THREAD

**Issue by amychaudhary** [razorpay/razorpay-android-sample-app#87]
I have an app which has dynamic pricing. If the user generates the bill and goes into Razorpay checkout page and stays there for a long time. The actual price deviates from the price paid. The razorpay doesn't time out the transaction. Is there any solution to this kind of problem which involves dynamic pricing?

**Comment by sumedht** [comment]
@amychaudhary Closing this issue due to no further communication. Please feel free to either re-open the issue or create a new issue if you have any additional queries.
