### ISSUE TITLE
Security Error on Web View

### ISSUE THREAD

**Issue by NehaSukhlecha** [razorpay/razorpay-android-sample-app#88]
Uncaught SecurityError: Blocked a frame with origin "https://api.razorpay.com" from accessing a frame with origin "https://xyzl.in". Protocols, domains, and ports must match.", source: https://checkout.razorpay.com/v1/checkout-frame.js

**Comment by SubhrajyotiSen** [comment]
Any updates on this?

**Comment by sumedht** [comment]
@SubhrajyotiSen @NehaSukhlecha Looks like u are opening checkout in webView. U can use SDK for this issue.

**Comment by nihar89** [comment]
I want to do payment through webview only but getting error:

 "Uncaught SecurityError: Blocked a frame with origin "https://api.razorpay.com" from accessing a frame with origin "http://192.168.0.121".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "http". Protocols must match.
    ", source: https://checkout.razorpay.com/v1/checkout-frame.js (1)

Any solution for this?

**Comment by abeegit** [comment]
Did anyone get a fix for this?

**Comment by annamalaicoderays** [comment]
`"Uncaught SecurityError: Blocked a frame with origin "https://api.razorpay.com" from accessing a frame with origin "https://xyz.com".  The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "http". Protocols must match.`

We are working on this last 3 weeks, on the project delivery time we got this error we tried to communicate with support team but the response is not clear. if any one got solution for the above problem pls post here

**Comment by annamalaicoderays** [comment]
```
$data = [
    "key"               => $keyId,
    "amount"            => $amount,
    "name"              => "DJ Tiesto",
    "description"       => "Tron Legacy",
    "image"             => "https://s29.postimg.org/r6dj1g85z/daft_punk.jpg",
    "prefill"           => [
    "name"              => "Daft Punk",
    "email"             => "customer@merchant.com",
    "contact"           => "9999999999",
    ],
    "notes"             => [
    "address"           => "Hello World",
    "merchant_order_id" => "12312321",
    ],
    "theme"             => [
    "color"             => "#F37254"
    ],
    "order_id"          => $razorpayOrderId,
    "callback_url"      =>'http://192.168.0.125/razorpay/verify_1.php?a=5',
];
```
 **"callback_url"      =>'http://192.168.0.125/razorpay/verify_1.php?a=5',**

**Add this call back url to your array**  so you  can easily fix this below error

`"Uncaught SecurityError: Blocked a frame with origin "https://api.razorpay.com" from accessing a frame with origin "https://xyz.com". The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "http". Protocols must match.`

Thank You

**Comment by ndc411** [comment]
> ```
> $data = [
>     "key"               => $keyId,
>     "amount"            => $amount,
>     "name"              => "DJ Tiesto",
>     "description"       => "Tron Legacy",
>     "image"             => "https://s29.postimg.org/r6dj1g85z/daft_punk.jpg",
>     "prefill"           => [
>     "name"              => "Daft Punk",
>     "email"             => "customer@merchant.com",
>     "contact"           => "9999999999",
>     ],
>     "notes"             => [
>     "address"           => "Hello World",
>     "merchant_order_id" => "12312321",
>     ],
>     "theme"             => [
>     "color"             => "#F37254"
>     ],
>     "order_id"          => $razorpayOrderId,
>     "callback_url"      =>'http://192.168.0.125/razorpay/verify_1.php?a=5',
> ];
> ```
> 
> **"callback_url" =>'http://192.168.0.125/razorpay/verify_1.php?a=5',**
> 
> **Add this call back url to your array** so you can easily fix this below error
> 
> `"Uncaught SecurityError: Blocked a frame with origin "https://api.razorpay.com" from accessing a frame with origin "https://xyz.com". The frame requesting access has a protocol of "https", the frame being accessed has a protocol of "http". Protocols must match.`
> 
> Thank You

callback is rejected 

https://api.razorpay.com/v1/payments/pay_DcaP2ikebbbBbS/callback/f876290dcd1873763427fb56c197a68f967bd440/rzp_test_UolxV8NXMDVCP4?status=failed&token_recurring_status=rejected

**Comment by ndc411** [comment]
@annamalaicoderays

**Comment by annamalaicoderays** [comment]
@ndc411 Please replace your server address, which means (**ip** or **domain** name)
` "callback_url" =>'http://[SERVER_ADDRESS]/razorpay/verify.php',`

**Comment by ndc411** [comment]
> @ndc411 Please replace your server address, which means (**ip** or **domain** name)
> and you should follow any one format like this (**https://domain_name.com** or **https://www.domain_name.com**)
> 
> ` "callback_url" =>'http://[SERVER_ADDRESS]/razorpay/verify.php',`

@annamalaicoderays   I am confused about the server address. Do you mean the webhooks url's domain which is at "https://dashboard.razorpay.com/#/app/webhooks" page?  Many thanks！

**Comment by annamalaicoderays** [comment]
@ndc411  are you using php integration for android??

**Comment by ndc411** [comment]
> @ndc411 are you using php integration for android??

I am sorry that I did not say clearly before. I’m doing testing now. I have to reuse the web integration for some reason. I want to reuse my web integration of Razorpay Checkout inside a web view on Android . I have read the doc: https://razorpay.com/docs/payment-gateway/callback-url/, and add 'callback_url'. so, what's the callback_url ?


here is options:
options = {
          "key": latestLoan.paymentKey,
          "amount": 5,
          "currency": "INR",
          "name": depositResult.name,
          "description": depositResult.description,
          "image": depositResult.image,
          "order_id": depositResult.orderId,
          "handler": function (response){
            window.location.href='success.html'
          },
          "prefill": {
            "name": name,
            "email": email,
            "contact": contact,
            "method": pageData.prefillMethod
          },
          "notes": {
            "address": "note value"
          },
          "theme": {
            "color": depositResult.color
          },
          "callback_url": '???',
          "redirect": true,
        };

**Comment by ndc411** [comment]
> @ndc411 are you using php integration for android??

I am sorry that I did not say clearly before. I’m doing testing now. I have to reuse the web integration for some reason. I want to reuse my web integration of Razorpay Checkout inside a web view on Android . I have read the doc: https://razorpay.com/docs/payment-gateway/callback-url/, and add 'callback_url'. so, what's the callback_url ?


here is options:
options = {
          "key": latestLoan.paymentKey,
          "amount": 5,
          "currency": "INR",
          "name": depositResult.name,
          "description": depositResult.description,
          "image": depositResult.image,
          "order_id": depositResult.orderId,
          "handler": function (response){
            window.location.href='success.html'
          },
          "prefill": {
            "name": name,
            "email": email,
            "contact": contact,
            "method": pageData.prefillMethod
          },
          "notes": {
            "address": "note value"
          },
          "theme": {
            "color": depositResult.color
          },
          "callback_url": '???',
          "redirect": true,
        };
@annamalaicoderays

**Comment by ndc411** [comment]
> @ndc411 are you using php integration for android??

Thank you for your patience. I reuse the web integration in our mobile app, then I replace our server address --- https://our-server/callback_url,  it can work normally.

**Comment by Nithinpj** [comment]
> > @ndc411 are you using php integration for android??
> 
> Thank you for your patience. I reuse the web integration in our mobile app, then I replace our server address --- https://our-server/callback_url, it can work normally.

how to integrate this in android webview

**Comment by mr-shitou** [comment]
> > @ndc411 are you using php integration for android??
> 
> Thank you for your patience. I reuse the web integration in our mobile app, then I replace our server address --- https://our-server/callback_url, it can work normally.

hi，can u explain 1 are you using php integration for android??
> 
> Thank you for your patience. I reuse the web integration in our mobile app, then I replace our server address --- https://our-server/callback_url, it can work normally.

hi，can u explain in more detial, thank u

**Comment by ndc411** [comment]
> > > @ndc411 are you using php integration for android??
> > 
> > 
> > Thank you for your patience. I reuse the web integration in our mobile app, then I replace our server address --- https://our-server/callback_url, it can work normally.
> 
> how to integrate this in android webview

the key of doc ： https://razorpay.com/docs/payment-gateway/web-integration/standard/#manual;

so you need to write a h5 with some css and js that abilities to process payments.  In the last, Deploy the application,   android webview call the application's url with parameters。

**Comment by mr-shitou** [comment]
I tried to deal with this problem and made some progress.
I just want use WebView，and get this problem.
There is my thinking，I override onCreateWindow method and fixup...
The rest is coding my own logic
You can search WebVIew Multi-window or can reference this link 
https://blog.maurizionapoleoni.com/opening-a-window-open-in-android-without-killing-the-content-of-the-main-webview/
Good luck and hope it help u

**Comment by sid25298** [comment]
I am getting an error {"error":{"code":"BAD_REQUEST_ERROR","description":"Input fields not set properly"}} in a new webview

**Comment by sumedht** [comment]
Closing this issue due to no further communication. Please feel free to either re-open the issue or create a new issue if you have any additional queries.
