### ISSUE TITLE
Success/Failure not receiving 

### ISSUE THREAD

**Issue by shishram** [razorpay/razorpay-android-sample-app#9]
I have implemented payment on Fragment, it opens up to get all the details but Success and Failure toast comes like mentioned below respectively

Error: onPaymentSuccess probably not implemented
Error: onPaymentError probably not implemented

Do I have to implement in Activity only?

**Comment by shashankmehta** [comment]
@shishram Yes, it has to be in the activity only and this is mentioned in the documentation too. Just move these two functions into your fragment's parent activity and it should work.

**Comment by shashankmehta** [comment]
Feel free to open this issue again in case you are not able to get it to work.

**Comment by shishram** [comment]
@shashankmehta Thanks, its working! But in documentation it's not that clear that one has to put these two methods in Parent activity if you're using a fragment. Thanks Again.

**Comment by shashankmehta** [comment]
@shishram We have this callout in the page:

<img width="1076" alt="screen shot 2016-06-08 at 5 12 34 pm" src="https://cloud.githubusercontent.com/assets/1315944/15893283/5111c1d4-2d9c-11e6-8565-77c2b61eb35e.png">

Let me know if you have suggestions on how it can be made more prominent, probably by placing it higher up or calling it out multiple times.

**Comment by shishram** [comment]
Like you can put few lines regarding implementation in readme file which are mentioned in documentaion of project so one does not have to read all the documentation to get it work. anyway Thanks for your help, really appreciated!

**Comment by maulik-dodia** [comment]
@shashankmehta Thanks a lot man.

**Comment by amiyo-biswas** [comment]
Faced same problem!

**Comment by crazycoderbabu** [comment]
Whenever I am putting like invalid card Expiry date or CVV the OnPaymentError method is not getting called. Please Help me. I have already spent lots of time on this error

**Comment by krmanohar** [comment]
facing the same problem if somebody entered wrong expiry date or CVV. the payment failed message appears for a fraction of a second and disappears. anybody has any luck in showing the payment failed message. Please share

**Comment by chitra-bahadur** [comment]
facing the same issue implemented in Activity and Fragment but not getting any error method neither any callback methods are getting called.

**Comment by sabinartificers** [comment]
I want to receive on success and failure in my fragment i can't use activity for that how can i implement razorpay

**Comment by 52280** [comment]
sir , i am integrating razor pay on fragment ,

public class RepaymentFragment extends Fragment implements PaymentResultListener {

    private static final String TAG = RepaymentFragment.class.getSimpleName();

    TextView tv_id,tv_repayment,tv_loanAmount,tv_tenure,tv_dispersableAmount,tv_fee;
    TextView tv_feegst,tv_interestrate,tv_repaymentAmount;

    String id,repaymentdate,loanamount,tenure,dsAmount,fee,feegst,ir,ra;
    TextView tv_pay;
    private final String YOUR_KEY_ID = "rzp_test_xmfEfgsIpkOoTR";
    //final String public_key = String.valueOf("sdfsdfsdfsdf");

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        View view = inflater.inflate(R.layout.fragment_repayment, container, false);
        Checkout.preload(getActivity());


        tv_id = view.findViewById(R.id.customerid);
        tv_repayment = view.findViewById(R.id.loanrepaymentdate);
        tv_loanAmount = view.findViewById(R.id.finalloanAmount);
        tv_tenure = view.findViewById(R.id.finaltenure);
        tv_dispersableAmount = view.findViewById(R.id.DispersableAmount);
        tv_fee = view.findViewById(R.id.processingfee);
        tv_feegst = view.findViewById(R.id.Gstprocessingfee);
        tv_interestrate = view.findViewById(R.id.totalinterestrate);
        tv_repaymentAmount = view.findViewById(R.id.totalpayment);

      /*  id = getIntent().getStringExtra("userid");
        repaymentdate = getIntent().getStringExtra("loanUpdatetime");
        loanamount = getIntent().getStringExtra("payableAmount");
        tenure = getIntent().getStringExtra("loanduration");
        dsAmount = getIntent().getStringExtra("loanAmount");
        fee = getIntent().getStringExtra("processingfee");
        feegst = getIntent().getStringExtra("gst");
        ir = getIntent().getStringExtra("InteresRate");
        ra = getIntent().getStringExtra("payableAmount");
*/
        tv_pay = view.findViewById(R.id.repayment);
        tv_pay.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                startPayment();
            }
        });
        return view;
    }
    public void startPayment() {


        final RepaymentFragment repaymentFragment = this;

        Checkout checkout = new Checkout();
        checkout.setKeyID("rzp_test_xmfEfgsIpkOoTR");
        //checkout.setImage(R.drawable.logo);

         try {
             JSONObject options = new JSONObject();
         options.put("name", "Merchant Name");
         options.put("description", "123456");
         options.put("image", "https://s3.amazonaws.com/rzp-mobile/images/rzp.png");
         options.put("order_id", "9A33XWu170gUtm");
         options.put("currency", "INR");
         options.put("amount", "500");

         JSONObject prefill = new JSONObject();
         prefill.put("email","appsbuilder941@gmail.com");
         prefill.put("name","vijay");
         options.put("prefil",prefill);

         checkout.open(getActivity(),options);
         }
         catch(Exception e) {

             Log.e(TAG, "Error in starting Razorpay Checkout", e);
             //Toast.makeText(getActivity(),"Error in payment"+e.getMessage(),Toast.LENGTH_LONG).show();
         }
    }


    @Override
    public void onPaymentSuccess(String s) {
        try {
            Toast.makeText(getActivity(),"sucess",Toast.LENGTH_LONG).show();
        }catch (Exception e){
            Log.e(TAG, "Exception in onPaymentSuccess", e);
        }

    }

    @Override
    public void onPaymentError(int i, String s) {

        //Toast.makeText(getActivity(),"failed",Toast.LENGTH_LONG).show();

        try {
            
            Toast.makeText(getActivity(), "Payment failed: "+i+""+s,Toast.LENGTH_SHORT).show();
        } catch (Exception e) {
            Log.e(TAG, "Exception in onPaymentError", e);
        }
    }
}
 and i am getting error like : 
Error: onPaymentError probably not implemented in your activity .
so , guide me how to solve it.

**Comment by moinahmed9999** [comment]
> and i am getting error like :
> Error: onPaymentError probably not implemented in your activity .
> so , guide me how to solve it.

@52280 
Implement the PaymentResultListener or PaymentResultWithDataListener(which I have done in the example) in the parent activity and notify the fragment about the event using a [ViewModel](https://developer.android.com/guide/fragments/communicate#viewmodel)
See : https://developer.android.com/guide/fragments/communicate#viewmodel

Create a ViewModel called SharedViewModel like:

    public class SharedViewModel extends ViewModel {
        private final MutableLiveData<Boolean> onSuccess = new MutableLiveData<>();
        private final MutableLiveData<Boolean> onError = new MutableLiveData<>();
    
        private PaymentError paymentError;
        private PaymentSuccess paymentSuccess;
    
        public LiveData<Boolean> getOnSuccess() {
            return onSuccess;
        }
    
        public LiveData<Boolean> getOnError() {
            return onError;
        }
    
        public void setOnSuccess(Boolean b) {
            onSuccess.setValue(b);
        }
    
        public void setOnError(Boolean b) {
            onError.setValue(b);
        }
    
        public PaymentError getPaymentError() {
            return paymentError;
        }
    
        public void setPaymentError(PaymentError paymentError) {
            this.paymentError = paymentError;
        }
    
        public PaymentSuccess getPaymentSuccess() {
            return paymentSuccess;
        }
    
        public void setPaymentSuccess(PaymentSuccess paymentSuccess) {
            this.paymentSuccess = paymentSuccess;
        }
    }

Now in your activity do this:

    private SharedViewModel sharedViewModel;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        ...
        ...

        sharedViewModel = new ViewModelProvider(this).get(SharedViewModel.class);
        sharedViewModel.setOnSuccess(false);
        sharedViewModel.setOnError(false);

        ...
        ...
    }
    
    @Override
    public void onPaymentSuccess(String razorpayPaymentId, PaymentData paymentData) {
        PaymentSuccess paymentSuccess = new PaymentSuccess(razorpayPaymentId, paymentData);

        sharedViewModel.setPaymentSuccess(paymentSuccess);
        sharedViewModel.setOnSuccess(true);
    }

    @Override
    public void onPaymentError(int code, String description, PaymentData paymentData) {
        PaymentError paymentError = new PaymentError(code, description, paymentData);

        sharedViewModel.setPaymentError(paymentError);
        sharedViewModel.setOnError(true);
    }

In the fragment do this without implementing the listener in it:

    private SharedViewModel sharedViewModel;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        ..
        ..

        Checkout.preload(getContext());

        sharedViewModel = new ViewModelProvider(requireActivity()).get(SharedViewModel.class);

        sharedViewModel.getOnSuccess().observe(getViewLifecycleOwner(), onSuccess -> {
            if (onSuccess) {
                PaymentSuccess success = sharedViewModel.getPaymentSuccess();

                onPaymentSuccess(success.getRazorpayPaymentId(), success.getPaymentData());
            }
        });

        sharedViewModel.getOnError().observe(getViewLifecycleOwner(), onError -> {
            if (onError) {
                PaymentError error = sharedViewModel.getPaymentError();

                onPaymentError(error.getCode(), error.getDescription(), error.getPaymentData());
            }
        });

        ..
        ..
    }
    
    public void onPaymentSuccess(String razorpayPaymentId, PaymentData paymentData) {
        sharedViewModel.setOnSuccess(false);
        Checkout.clearUserData(getContext());
        
        // Do something
    }

    public void onPaymentError(int code, String description, PaymentData paymentData) {
        sharedViewModel.setOnError(false);
        Checkout.clearUserData(getContext());

        // Do something
    }

The classes PaymentError and PaymentSuccess are :

    public class PaymentSuccess {
        private String razorpayPaymentId;
        private PaymentData paymentData;
    
        public PaymentSuccess(String razorpayPaymentId, PaymentData paymentData) {
            this.razorpayPaymentId = razorpayPaymentId;
            this.paymentData = paymentData;
        }
    
        public String getRazorpayPaymentId() {
            return razorpayPaymentId;
        }
    
        public PaymentData getPaymentData() {
            return paymentData;
        }
    }

    public class PaymentError {
        private int code;
        private String description;
        private PaymentData paymentData;
    
        public PaymentError(int code, String description, PaymentData paymentData) {
            this.code = code;
            this.description = description;
            this.paymentData = paymentData;
        }
    
        public int getCode() {
            return code;
        }
    
        public String getDescription() {
            return description;
        }
    
        public PaymentData getPaymentData() {
            return paymentData;
        }
    }

**Comment by Mustangodhra** [comment]
> > and i am getting error like :
> > Error: onPaymentError probably not implemented in your activity .
> > so , guide me how to solve it.
> 
> @52280
> Implement the PaymentResultListener or PaymentResultWithDataListener(which I have done in the example) in the parent activity and notify the fragment about the event using a [ViewModel](https://developer.android.com/guide/fragments/communicate#viewmodel)
> See : https://developer.android.com/guide/fragments/communicate#viewmodel
> 
> Create a ViewModel called SharedViewModel like:
> 
> ```
> public class SharedViewModel extends ViewModel {
>     private final MutableLiveData<Boolean> onSuccess = new MutableLiveData<>();
>     private final MutableLiveData<Boolean> onError = new MutableLiveData<>();
> 
>     private PaymentError paymentError;
>     private PaymentSuccess paymentSuccess;
> 
>     public LiveData<Boolean> getOnSuccess() {
>         return onSuccess;
>     }
> 
>     public LiveData<Boolean> getOnError() {
>         return onError;
>     }
> 
>     public void setOnSuccess(Boolean b) {
>         onSuccess.setValue(b);
>     }
> 
>     public void setOnError(Boolean b) {
>         onError.setValue(b);
>     }
> 
>     public PaymentError getPaymentError() {
>         return paymentError;
>     }
> 
>     public void setPaymentError(PaymentError paymentError) {
>         this.paymentError = paymentError;
>     }
> 
>     public PaymentSuccess getPaymentSuccess() {
>         return paymentSuccess;
>     }
> 
>     public void setPaymentSuccess(PaymentSuccess paymentSuccess) {
>         this.paymentSuccess = paymentSuccess;
>     }
> }
> ```
> 
> Now in your activity do this:
> 
> ```
> private SharedViewModel sharedViewModel;
> 
> @Override
> protected void onCreate(Bundle savedInstanceState) {
>     ...
>     ...
> 
>     sharedViewModel = new ViewModelProvider(this).get(SharedViewModel.class);
>     sharedViewModel.setOnSuccess(false);
>     sharedViewModel.setOnError(false);
> 
>     ...
>     ...
> }
> 
> @Override
> public void onPaymentSuccess(String razorpayPaymentId, PaymentData paymentData) {
>     PaymentSuccess paymentSuccess = new PaymentSuccess(razorpayPaymentId, paymentData);
> 
>     sharedViewModel.setPaymentSuccess(paymentSuccess);
>     sharedViewModel.setOnSuccess(true);
> }
> 
> @Override
> public void onPaymentError(int code, String description, PaymentData paymentData) {
>     PaymentError paymentError = new PaymentError(code, description, paymentData);
> 
>     sharedViewModel.setPaymentError(paymentError);
>     sharedViewModel.setOnError(true);
> }
> ```
> 
> In the fragment do this without implementing the listener in it:
> 
> ```
> private SharedViewModel sharedViewModel;
> 
> @Override
> public View onCreateView(LayoutInflater inflater, ViewGroup container,
>                          Bundle savedInstanceState) {
>     ..
>     ..
> 
>     Checkout.preload(getContext());
> 
>     sharedViewModel = new ViewModelProvider(requireActivity()).get(SharedViewModel.class);
> 
>     sharedViewModel.getOnSuccess().observe(getViewLifecycleOwner(), onSuccess -> {
>         if (onSuccess) {
>             PaymentSuccess success = sharedViewModel.getPaymentSuccess();
> 
>             onPaymentSuccess(success.getRazorpayPaymentId(), success.getPaymentData());
>         }
>     });
> 
>     sharedViewModel.getOnError().observe(getViewLifecycleOwner(), onError -> {
>         if (onError) {
>             PaymentError error = sharedViewModel.getPaymentError();
> 
>             onPaymentError(error.getCode(), error.getDescription(), error.getPaymentData());
>         }
>     });
> 
>     ..
>     ..
> }
> 
> public void onPaymentSuccess(String razorpayPaymentId, PaymentData paymentData) {
>     sharedViewModel.setOnSuccess(false);
>     Checkout.clearUserData(getContext());
>     
>     // Do something
> }
> 
> public void onPaymentError(int code, String description, PaymentData paymentData) {
>     sharedViewModel.setOnError(false);
>     Checkout.clearUserData(getContext());
> 
>     // Do something
> }
> ```
> 
> The classes PaymentError and PaymentSuccess are :
> 
> ```
> public class PaymentSuccess {
>     private String razorpayPaymentId;
>     private PaymentData paymentData;
> 
>     public PaymentSuccess(String razorpayPaymentId, PaymentData paymentData) {
>         this.razorpayPaymentId = razorpayPaymentId;
>         this.paymentData = paymentData;
>     }
> 
>     public String getRazorpayPaymentId() {
>         return razorpayPaymentId;
>     }
> 
>     public PaymentData getPaymentData() {
>         return paymentData;
>     }
> }
> 
> public class PaymentError {
>     private int code;
>     private String description;
>     private PaymentData paymentData;
> 
>     public PaymentError(int code, String description, PaymentData paymentData) {
>         this.code = code;
>         this.description = description;
>         this.paymentData = paymentData;
>     }
> 
>     public int getCode() {
>         return code;
>     }
> 
>     public String getDescription() {
>         return description;
>     }
> 
>     public PaymentData getPaymentData() {
>         return paymentData;
>     }
> }
> ```

I tried this code but i am getting an error which shows:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.saiftechnology.eventpool, PID: 15810
    java.lang.RuntimeException: **Unable to start activity ComponentInfo{com.saiftechnology.eventpool/com.saiftechnology.eventpool.student.studentAccount}: java.lang.RuntimeException: Cannot create an instance of class com.saiftechnology.eventpool.student.eventDetailsFragment$SharedViewModel**
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3311)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3460)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7590)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     **Caused by: java.lang.RuntimeException: Cannot create an instance of class com.saiftechnology.eventpool.student.eventDetailsFragment$SharedViewModel**
        at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:221)
        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:278)
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:112)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        **at com.saiftechnology.eventpool.student.studentAccount.onCreate(studentAccount.java:40)**
        at android.app.Activity.performCreate(Activity.java:7893)
        at android.app.Activity.performCreate(Activity.java:7880)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3286)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3460) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.app.ActivityThread.main(ActivityThread.java:7590) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
     Caused by: java.lang.InstantiationException: java.lang.Class<com.saiftechnology.eventpool.student.eventDetailsFragment$SharedViewModel> has no zero argument constructor
        at java.lang.Class.newInstance(Native Method)
        at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:219)
        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:278) 
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:112) 
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185) 
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150) 
        at com.saiftechnology.eventpool.student.studentAccount.onCreate(studentAccount.java:40) 
        at android.app.Activity.performCreate(Activity.java:7893) 
        at android.app.Activity.performCreate(Activity.java:7880) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3286) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3460) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2047) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.app.ActivityThread.main(ActivityThread.java:7590) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
I/ology.eventpoo: ProcessProfilingInfo new_methods=2208 is saved saved_to_disk=1 resolve_classes_delay=8000
 

the code which is pointed in the error (studentAccount.java:40) is:
**sharedViewModel = new ViewModelProvider(this).get(eventDetailsFragment.SharedViewModel.class);**

Appreciate your help.

**Comment by nikharsachdeva** [comment]
> Whenever I am putting like invalid card Expiry date or CVV the OnPaymentError method is not getting called. Please Help me. I have already spent lots of time on this error

Any luck?

**Comment by nikharsachdeva** [comment]
> facing the same problem if somebody entered wrong expiry date or CVV. the payment failed message appears for a fraction of a second and disappears. anybody has any luck in showing the payment failed message. Please share

Any solution/reason found?

**Comment by Mustangodhra** [comment]
@nikharsachdeva you have to implement the listener in the parent/container activity.

**Comment by Mustangodhra** [comment]
@nikharsachdeva refer this sample code:

`    public class parentClass extends AppCompatActivity implements PaymentResultWithDataListener {

    //onCreate code........ 

    public void onPaymentSuccess(String razorpayPaymentId, PaymentData paymentData) {
        
        Toast.makeText(getApplicationContext, "success", Toast.LENGTH_SHORT).show();

    }
    public void onPaymentError(int code, String description, PaymentData paymentData) {

        Toast.makeText(getApplicationContext, "failed", Toast.LENGTH_SHORT).show();

    }
}`
