### ISSUE TITLE
How to implement Subscription/Recurring payments using Razorpay Android SDK?

### ISSUE THREAD

**Issue by gauravk95** [razorpay/razorpay-android-sample-app#92]
I cannot find a way to implement Subscription/Recurring Payments using the Razorpay's Android SDK?
Is there any easy way to do this or I have to use the Web API only, to achieve this?

Also the Web API doesn't seem to work... 
Says "the request URL doesn't exist on the server...Here's a snapshot
![razorpay-bug](https://user-images.githubusercontent.com/15252140/49373844-80b50e00-f725-11e8-9658-6d41f2d2b1fc.JPG)

**Comment by jamilxt** [comment]
did you able to pull it off?

**Comment by sumedht** [comment]
Closing this issue due to no further communication. Please feel free to either re-open the issue or create a new issue if you have any additional queries.

**Comment by pmpavan** [comment]
Any documentation to help integrate subscription using RazorPay Android SDK?

**Comment by sumedht** [comment]
@razorpay/techpgintegrations plz help with this

**Comment by PraveenGirishNadumani** [comment]
@pmpavan  Subscription/Recurring is the backend implementation, please follow the [subscription doc](https://razorpay.com/docs/api/subscriptions/) and for Android follow the same steps mentioned in the [Android doc](https://razorpay.com/docs/payment-gateway/android-integration/standard/). While [initiating](https://razorpay.com/docs/payment-gateway/android-integration/standard/#initiate-a-payment) the payment just replace order_id with the subscritpion_id and Razorpay SDK is smart enough to identify it's a recurring payment.
