### ISSUE TITLE
onPaymentSuccess not getting called on Success

### ISSUE THREAD

**Issue by gvirmani** [razorpay/razorpay-android-sample-app#93]
We have implemented the Checkout as per the sample code. Issue is the OnPaymentSuccess method isn't being called on Success.  During debugging found that the activity is getting destroyed on checkout.open call. The success method is called only 1 out of 10 times during our testing. Moved to live mode but still same issue.

**Comment by sumedht** [comment]
@gvirmani Need some details like
- Have u added proguard rules?
- Device config on which u getting crash? 
- use latest version of sdk 1.5.1
