### ISSUE TITLE
Razorpay assist not working for 'enter password' for verified by visa and mastercard secure code pages

### ISSUE THREAD

**Issue by kusu108** [razorpay/razorpay-android-sample-app#94]
Only for razorpay latest sdk. For axis bank gateways, razorpay assist opens, on clicking enter a password in assist nothing happens. OTP works as desired but 'verified by visa' and 'Mastercard securecode' shows non-responsiveness. Screen [video](https://www.youtube.com/watch?v=tbwn-fkCUjw&t=5s) attached.

**Comment by sumedht** [comment]
Closing this issue due to no further communication. Please feel free to either re-open the issue or create a new issue if you have any additional queries.
